FunkinCrew/Funkin

- source/StoryMenuState.hx
The story menu buttons can be spammed a lot so made a quick fix if it bothers
> fixed spamming issue with the buttons on the story menu

- source/MainMenuState.hx
- source/PlayState.hx
- source/TitleState.hx
Some bugs related to music.
- Going to Freeplay mode then exits immediately causes the music volume to stop going up
- Returning to Main Menu (from exiting/finishing the gane) doesnt play main menu music
- Pausing the game right when the song started doenst stop the song, but it continues playing
- Pausing early in the game (during the 3 beat countdown), then unpausing the game, will play previous song until the countdown finishes
Related issues: #16 #50
> Music issues throughout the game

- CHANGELOG.md
- LICENSE
- Project.xml
- README.md
- assets/data/introText.txt
- assets/data/specialThanks.txt
- assets/mods/introMod/_append/data/introText.txt
- source/Alphabet.hx
- source/BackgroundDancer.hx
- source/Character.hx
- source/ChartingState.hx
- source/Controls.hx
- source/DialogueBox.hx
- source/FreeplayState.hx
- source/GameOverState.hx
- source/HealthIcon.hx
- source/MainMenuState.hx
- source/MenuCharacter.hx
- source/MenuItem.hx
- source/Note.hx
- source/OptionsMenu.hx
- source/PlayState.hx
- source/StoryMenuState.hx
- source/TitleState.hx
Sorry about the weird formatting bruv i've never coded in Haxe but I wanted to give it a shot and I've got the enemies dying faces to work. Can't say that it's optimized or whatnot, but I thought it may help :)? I dunno.
> Add enemies' dying faces

- source/Character.hx
- source/PlayState.hx
fixes invalid asset paths on the pico stage
> fix pico asset paths

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE/enhancement.md
> Basic PR/Issue templates

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE/enhancement.md
I had made some mistakes when I first submmited this PR as far as formatting and markdown goes.
Similar to #327.
> Update Issue Templates

- source/PlayState.hx
Changes the static arrows code to use switch case "or" instead of copy pasting. hopefully will make things neater in the future.
> Use haxe switch case 'or'

- README.md
Haxe 4.2.0 wasn't working, so I edited the guide to fix it and download Haxe 4.1.5 instead.
> Edited README to fix compiling issue

- README.md
adds information on how to fix transition bug atm, can be removed once flixel-addons gets a new release
> add transition fix to readme

- Project.xml
- README.md
- source/Discord.hx
- source/FreeplayState.hx
- source/PlayState.hx
- source/StoryMenuState.hx
- source/TitleState.hx
Cool little addition that adds Discord Rich Presence. Needs a new library which you can download with:
`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc` which also downloads hxcpp if you don't have it already.
> Discord RPC (custom status)

- source/PlayState.hx
allows girlfriend to cheer in the tutorial by moving the if statement for tutorial outside of the one for bopeebo
additionally, make it work in conjunction with the tutorial audio itself
https://user-images.githubusercontent.com/15317421/109366979-ae785700-7849-11eb-8f09-194f0180c93b.mp4
> girlfriend cheering in tutorial

- source/PlayState.hx
Use a `switch` statement instead of huge `if .. else if` chains.
> feat(performance): Use switch statement

- source/funkin/play/event/PlayAnimationSongEvent.hx
A thousand curses upon your bloodline for not testing your PR before pushing it, @BurgerBalls
> Fix a typo in PlayAnimationSongEvent

- README.md
Simple PR, the title says it all.
> Specify `credits.json` in README

- README.md
Reverts FunkinCrew/Funkin#2325
don't merge shit into main
> Revert "Specify `credits.json` in README"

- source/funkin/play/PlayState.hx
Multiple times I've pressed the chart key while already chart play-testing and lost my chart
This makes it just take you back to the chart editor if you press it while testing
> Chart debug key takes you back to chart editor if you're charting

- source/funkin/ui/freeplay/FreeplayState.hx
Selfexplained
https://github.com/FunkinCrew/Funkin/assets/55158797/61ec0e5d-3d74-4225-b420-b89c0b012875
> Fixed doing actions when exiting Freeplay menu

- source/funkin/ui/freeplay/FreeplayState.hx
Before this fix, scrolling through songs in the freeplay menu using the scroll wheel would not function as expected. This pull request fixes this problem.
> Fixed Freeplay Scrolling Issue

- source/funkin/input/Controls.hx
This would cause the game to freeze as the game would try to load all the keybinds.
> Fix an issue where control binds would be duplicated and quickly multiply.

- docs/Funkin' Debug Hotkeys.md
Update the documentation on debug hotkeys.
> Update Funkin' Debug Hotkeys.md

- docs/COMPILING.md
Coming from my own experience cloning this repo, this fix guide may help people with poor and/or slow connectivity. Both the base, art, and assets repo are big repos, and to fail them midway would be devastating as they would need to start the clone over.
Additional links:
- [Relevant StackOverflow discussion](https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-erro)
> Add a fix guide for those with poor internet connection

- .vscode/launch.json
Pretty useful for testing when you did no changes to the source.
> Add debugging without compiling to VSCode

- source/funkin/api/newgrounds/NGUnsafe.hx
- source/funkin/api/newgrounds/NGio.hx
- source/funkin/audio/FunkinSound.hx
- source/funkin/audio/VoicesGroup.hx
- source/funkin/audio/visualize/ABotVis.hx
- source/funkin/audio/visualize/PolygonVisGroup.hx
- source/funkin/audio/visualize/SpectogramSprite.hx
- source/funkin/audio/visualize/VisShit.hx
- source/funkin/audio/visualize/dsp/FFT.hx
- source/funkin/audio/waveform/WaveformData.hx
- source/funkin/audio/waveform/WaveformSprite.hx
- source/funkin/data/dialogue/conversation/ConversationData.hx
- source/funkin/data/dialogue/conversation/ConversationRegistry.hx
Removed a lot of unused imports and comments in a lot of files I wasn't able to fully do all files though do to how many there were
from my knowledge this does not cause any bugs or break the game in any ways 
(only tested on Windows 11)
> Remove alot of unused imoprts and comments (not even half)

- source/funkin/ui/debug/DebugMenuSubState.hx
- source/funkin/ui/mainmenu/MainMenuState.hx
fixes #2569
also removed one useless line in Debug Menu (lol)
> [BUGFIX] Main Menu Camera Fix

- source/funkin/play/stage/Stage.hx
This pr fixes Dad and Girlfriend characters using custom Boyfriend character scale in Stage.hx.
> [BUGFIX] Correct characters scaling on stage

- source/funkin/play/PlayState.hx
Yeah, i dont think it even needs a video
(Thx @Matriculaso for showing me this way to fix it, credit him not me!!)
it also uses `Constants.DEFAULT_CAMERA_FOLLOW_RATE` instead of 0.04
> [BUGFIX] Pause Camera Follow when pausing

- source/funkin/play/PlayState.hx
Copied opponent's holdTimer code to the player's side to process hold note animations correctly in Botplay mode
> Fix botplay sustain release bug

- .github/ISSUE_TEMPLATE/bug.md
> Fixed that one mistake in .github/ISSUE_TEMPLATE/bug.md

- source/funkin/ui/MenuList.hx
> chore: update MenuList.hx

- docs/troubleshooting.md
> [DOCS] Update to troubleshooting guide

- example_mods/introMod/_polymod_meta.json
- example_mods/testing123/_polymod_meta.json
None
Fixes example mods not loading due to outdated API version.
~~Does someone even use these?~~
> Chore: Upgrade Example Mods to latest API version

- .gitmodules
- CHANGELOG.md
Documented all the changes and fixes between v0.5.0 and v0.5.1
> [DOCS] Update changelog for v0.5.1

- source/funkin/ui/debug/latency/LatencyState.hx
Fixes #3489
Adds an if check before setting music volume in `LatencyState`
> Fix an issue where LatencyState crashes when exiting

- source/funkin/ui/debug/charting/ChartEditorState.hx
Minor change, but this makes the song time in the chart editor follow a proper time format.
Before:
After:
> Enhancement: Properly format the chart editor playbar

- CHANGELOG.md
- hmm.json
> Exiting the chart editor doesn't crash the game anymore

- source/funkin/modding/PolymodHandler.hx
This should be self-explanatory.
> chore: Blacklist an additional class in Polymod.

- CHANGELOG.md
Did some cleanup and added some missing entries.
> Rewrite CHANGELOG.md for v0.5.2

- CHANGELOG.md
> chore: Fix a typo in `CHANGELOG.md`

- .github/workflows/label-issue.yml
> Remove duplicate issue detector.

- LICENSE.md
no
It kinda “fixes” the Apache 2.0 part, just the start was using a ```code block``` and the rest was in Markdown
**Before:**
**After:**
> "Fixed" the Apache 2.0 LICENSE file part

- source/funkin/modding/IScriptedClass.hx
- source/funkin/modding/events/ScriptEvent.hx
- source/funkin/modding/events/ScriptEventDispatcher.hx
- source/funkin/modding/module/Module.hx
- source/funkin/play/PauseSubState.hx
- source/funkin/play/PlayState.hx
- source/funkin/play/notes/Strumline.hx
- source/funkin/play/notes/SustainTrail.hx
- source/funkin/play/song/Song.hx
- source/funkin/play/stage/Bopper.hx
- source/funkin/play/stage/Stage.hx
N/A
This is a merged PR of my previous ones that contain all of my recent modding changes.
This PR contains:
- `USE_CUSTOM_RENDER_DISTANCE:Bool`, and `CUSTOM_RENDER_DISTANCE_MS:Float` in Strumline.hx to allow for custom render distances.
- `customVertexData:Bool`, `setIndices(indices:Array<Int>):Void`, `setVertices(vertices:Array<Float>):Void`, and `setUVTData(uvtData:Array<Float>):Void` in SustainTrail.hx to allow for custom hold note vertices, uvs, and indicies.
- Updates onSongRetry to `onSongRetry(event:SongRetryEvent):Void` which now contains a `difficulty:String` field. This allows scripts to react to difficulty changes.
- `showNotesplash:Bool` into Strumline.hx. This will allow for scripts to disable note splashes on a song-by-song basis, and later for the game to add a notesplash …
> [ENHANCEMENT] [MODDING] Several QOL modding changes

- source/funkin/Assets.hx
This PR adds documentation for the last 3 functions in `funkin.Assets`, pretty self-explanatory. There were no comments for these functions in `openfl.utils.Assets`, so I had to write them myself.
If you have ideas for revisions, let me know!
> [DOCS] Add missing comments to 3 functions in `funkin.Assets`

- source/funkin/data/stage/StageData.hx
- source/funkin/play/stage/Stage.hx
Implements/Fixes #3719 (For scroll factor only)
This PR adds 3 new properties to stage data, specifically for characters: `angle`, `scroll`, and `alpha`.
These behave basically the same as how you would use them on a prop.
I also fixed a grammatical error in one of the comments for `StageData.hx`
<sub>Dinnerbone.</sub>
> [ENHANCEMENT] More Stage Data additions + Grammatical fix

- source/funkin/ui/debug/anim/DebugBoundingState.hx
This simple Pull Request adds the ability to horizontally flip the character in the Animation Editor (By pressing G). This can help a lot, especially when setting offsets for playable characters! Should be a decent quality-of-life feature.
I've created a PR on the assets repository (see [funkin.assets#60](https://github.com/FunkinCrew/funkin.assets/pull/60)) to add the keybind to the Shortcuts list.
https://github.com/user-attachments/assets/c7fd4e84-9753-47cf-af7b-2d9848211c96
> [ENHANCEMENT] Add the ability to flip the character in the Animation Editor

- docs/CONTRIBUTING.md
Adds 7 more rejected features to the Contributing Guide
> Add more rejected features to Contributing Guide

- docs/CONTRIBUTING.md
- Added a Charting PR section in the `funkin.assets` section
- This explains the guidelines for making a charting PR!
- Made code comments its own section and added more examples
- Some general polish I guess
> [DOCS] Some additions to the Contributor's Guide

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/charting.yml
- .github/ISSUE_TEMPLATE/compiling.yml
- .github/ISSUE_TEMPLATE/crash.yml
- docs/CONTRIBUTING.md
- docs/Funkin' Debug Hotkeys.md
Like https://github.com/FunkinCrew/Funkin/pull/4341, but for 0.6.1
> [GITHUB + DOCS] Update Issue Templates and CONTRIBUTING.md to 0.6.1

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/charting.yml
- .github/ISSUE_TEMPLATE/compiling.yml
- .github/ISSUE_TEMPLATE/crash.yml
- docs/CONTRIBUTING.md
Bump templates and docs again for the 0.6.2 hotfix
> Bump repo versions to 0.6.2

- .gitmodules
Annoying we have to do this every time
> Use public URLs for git submodules

- docs/CONTRIBUTING.md
Reverts a reversion of the Contributing Guide back to 0.5.3, back to 0.6.2 :trollface:
> [DOCS] Restore Contributing Guide to latest version

- docs/COMPILING.md
- docs/TROUBLESHOOTING.md
N/A
With the change of the Lime commit the information became outdated, this PR addresses that.
It now also guides the user in case they have a system with an older GLibC and run into a problem.
N/A
> [DOCS] Update Linux troubleshooting

- CHANGELOG.md
* Adds two more entries to the Changelog I noticed recently
* Removes duplicate entry about preference descriptions.
> [DOCS] Two more Chart Editor entries in Changelog

- docs/CONTRIBUTING.md
Cool lookin', but scrapped content!
> [DOCS] Add Combo Milestones to Rejected Features list

- docs/COMPILING.md
By recommending Funkin's fork of Lime, we avoid issues with some git repositories such as Lime.
> Recommend Funkin's fork of hmm

- docs/COMPILING.md
> [DOCS] Rewrote recommendation to use Funkin haxelib and hmm

- CHANGELOG.md
Lists all but a few changes introduced in 0.6.3
May revise later, but submitting this now to help players understand new changes!
> [DOCS] Changelog for 0.6.3

- CHANGELOG.md
I don't think this one requires much explanation.
> Remove leftover from merge-conflict in CHANGELOG

- CHANGELOG.md
* Credits Lasercar for fixing a crash and links commit/PR info
* Moves ShadzXD's contribution to the correct section of the Changelog.
Gotta make sure we're crediting those assets PRs!
> [DOCS] Credit Lasercar for a crash fix from an assets PR

- docs/CONTRIBUTING.md
Updated the Contributing Guide to reflect that we will no longer be accepting chart modifications in the `funkin.assets` repo.
If you notice an error in the chart metadata, you may still submit a PR!
Otherwise, please open an issue in the `Funkin` repo.
> [DOCS] Update Charting PR policy in Contributing Guide

- CHANGELOG.md
While I was rebasing PRs and resolving merge-conflicts, I noticed this error in the changelog on the develop branch.
> Remove another error from a merge-conflict in CHANGELOG

- source/funkin/play/PlayState.hx
Closes #4273
Adds a none/null option to the character dropdown. 
Also fixes a few null reference errors when one or both of the characters in the playstate are null.
https://github.com/user-attachments/assets/f843f36e-ba83-4d4d-822c-dedf41516925
> Chart editor - None character

- source/funkin/InitState.hx
- source/funkin/play/PlayState.hx
> FlxG.fixedTimestep=false

- .gitmodules
- CHANGELOG.md
- docs/COMPILING_MAC.md
- source/funkin/api/newgrounds/Events.hx
- source/funkin/api/newgrounds/Leaderboards.hx
- source/funkin/api/newgrounds/Medals.hx
- source/funkin/audio/visualize/ABotVis.hx
- source/funkin/graphics/adobeanimate/FlxAtlasSprite.hx
- source/funkin/play/PlayState.hx
- source/funkin/play/ResultState.hx
- source/funkin/play/character/CharacterData.hx
- source/funkin/save/Save.hx
- source/funkin/ui/PixelatedIcon.hx
- source/funkin/ui/charSelect/CharSelectGF.hx
- source/funkin/ui/charSelect/CharSelectSubState.hx
- source/funkin/ui/debug/anim/DebugBoundingState.hx
- source/funkin/ui/debug/results/ResultsDebugSubState.hx
- source/funkin/ui/freeplay/FreeplayDJ.hx
- source/funkin/ui/freeplay/FreeplayState.hx
- source/funkin/ui/options/PreferencesMenu.hx
- source/funkin/ui/title/TitleState.hx
- source/funkin/ui/transition/LoadingState.hx
- source/funkin/ui/transition/StickerSubState.hx
This pull request fixes a crash on entering animation editor just by adding a null check.
> [BUGFIX] Fix Animation Editor Crash

- .gitmodules
- CHANGELOG.md
- docs/COMPILING_MAC.md
- source/funkin/api/newgrounds/Events.hx
- source/funkin/api/newgrounds/Leaderboards.hx
- source/funkin/api/newgrounds/Medals.hx
- source/funkin/audio/visualize/ABotVis.hx
- source/funkin/graphics/adobeanimate/FlxAtlasSprite.hx
- source/funkin/play/PlayState.hx
- source/funkin/play/ResultState.hx
- source/funkin/play/character/CharacterData.hx
- source/funkin/save/Save.hx
- source/funkin/ui/PixelatedIcon.hx
- source/funkin/ui/charSelect/CharSelectGF.hx
- source/funkin/ui/charSelect/CharSelectSubState.hx
- source/funkin/ui/debug/results/ResultsDebugSubState.hx
- source/funkin/ui/freeplay/FreeplayDJ.hx
- source/funkin/ui/freeplay/FreeplayState.hx
- source/funkin/ui/options/PreferencesMenu.hx
- source/funkin/ui/title/TitleState.hx
- source/funkin/ui/transition/LoadingState.hx
- source/funkin/ui/transition/StickerSubState.hx
Fixes https://github.com/FunkinCrew/Funkin/issues/4571
View title
> [BUGFIX] Set Save's `_instance` to the loaded Save if null

- .gitmodules
- CHANGELOG.md
- docs/COMPILING_MAC.md
- source/funkin/api/newgrounds/Events.hx
- source/funkin/api/newgrounds/Leaderboards.hx
- source/funkin/api/newgrounds/Medals.hx
- source/funkin/audio/visualize/ABotVis.hx
- source/funkin/data/freeplay/player/PlayerRegistry.hx
- source/funkin/data/song/SongRegistry.hx
- source/funkin/data/stage/StageRegistry.hx
- source/funkin/data/story/level/LevelRegistry.hx
- source/funkin/graphics/adobeanimate/FlxAtlasSprite.hx
- source/funkin/play/PlayState.hx
- source/funkin/play/ResultState.hx
- source/funkin/play/character/CharacterData.hx
- source/funkin/save/Save.hx
- source/funkin/ui/PixelatedIcon.hx
- source/funkin/ui/charSelect/CharSelectGF.hx
- source/funkin/ui/charSelect/CharSelectSubState.hx
- source/funkin/ui/debug/results/ResultsDebugSubState.hx
- source/funkin/ui/freeplay/FreeplayDJ.hx
- source/funkin/ui/freeplay/FreeplayState.hx
- source/funkin/ui/options/PreferencesMenu.hx
- source/funkin/ui/title/TitleState.hx
- source/funkin/ui/transition/LoadingState.hx
- source/funkin/ui/transition/StickerSubState.hx
- source/funkin/util/macro/DataMacro.hx
https://github.com/FunkinCrew/Funkin/pull/4699#issuecomment-2798901739
this pr adds a macro that retrieves the base game stages
> [FEATURE] Use Macro For Base Game Assets

- .gitmodules
- source/funkin/ui/debug/charting/ChartEditorState.hx
Closes https://github.com/FunkinCrew/Funkin/issues/4641
Adds the current beat and step next to the song position.
https://github.com/user-attachments/assets/b592e9f0-b82f-4e1d-a99d-b7ce25d41a88
> [ENHANCEMENT] Chart Editor - Display current beat & step

- source/funkin/ui/options/PreferencesMenu.hx
Closes #4342 
Renamed the `Auto Pause` preference to `Pause on Unfocus` so that it is actually comprehensible without reading the description.
> Rename “Auto Pause” Preference to “Pause on Unfocus”

- source/funkin/ui/freeplay/FreeplayState.hx
Fixes https://github.com/FunkinCrew/Funkin/issues/4920
Fixes https://github.com/FunkinCrew/Funkin/pull/4898
https://github.com/FunkinCrew/Funkin/pull/4898#issuecomment-2842190730
> [BUGFIX] Fix `Fix Fix scoring changes`

- source/funkin/play/PlayState.hx
- source/funkin/ui/freeplay/FreeplayScore.hx
Original PRs: #4065 and #4279
We lost two of Lasercar's commits while merging a ton of stuff, so we're bringing them back.
> <RECOVERY> Restore two of Lasercar's commits

- source/funkin/modding/PolymodHandler.hx
- source/funkin/ui/debug/charting/ChartEditorState.hx
- source/funkin/ui/debug/stageeditor/StageEditorState.hx
- source/funkin/ui/debug/stageeditor/components/BackupAvailableDialog.hx
- source/funkin/util/FileUtil.hx
- source/funkin/util/WindowUtil.hx
Cherry-picks the other 2 commits from #3032 for 0.6.4 since it has conflicts.
NOTE: DO NOT CREDIT ME!!! CREDIT cyn0x8 FOR THE COMMITS!!!!
PR will be closed if #3032 gets its merge conflicts resolved before this PR is merged.
> 2 more commits from #3032

- CHANGELOG.md
- project.hxp
Adds the CHANGELOG for 0.6.4 and bumps the game version to 0.6.4, thank you to everyone who contributed to this patch!
> [DOCS] CHANGELOG for 0.6.4 + Bump version to 0.6.4

- CHANGELOG.md
I can't believe you didn't notice that #4936 was the first PR by CrusherNotDrip to be accepted.
> [DOCS] Add a Missing New Contributor for 0.6.4

- docs/TRACY.md
This should help out the people trying to diagnose issues like #4602, #4467, and #4761.
> [DOCS] Add documentation for using Tracy profiler

- docs/CONTRIBUTING.md
Adds "New intro texts" (#5031) and removes a few entries.
> [DOCS] Changes to the Contributing Guide's rejected features

- .github/pull_request_template.md
Nope
Moved instructions to not display on submission
> [GITHUB] Clean up PR Template

- CHANGELOG.md
This pull request adds a missing first-time contributor to the changelog for v0.6.4.
> [DOCS] Add a missing first-time contributor to v0.6.4 changelog

- .github/changed-lines-count-labeler.yml
Merges `main` into `develop`, just like #5093!
> [CHORE + GITHUB] Merge main into develop, again edition

- source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx
Fixes #4307
Watch video. ~~if pictures are worth a thousand words, then imagine how many words a 25 framerate * 13 second video is worth~~
https://github.com/user-attachments/assets/4364efc3-5a2e-472f-8592-f6c1c081ce68
> Chart editor - Clear un/redo history on song load

- project.hxp
No explanation needed. It's now formatted neatly like the rest of the game's codebase.
> chore: Format the `project.hxp` file

- source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx
- source/funkin/util/FileUtil.hx
No.
https://github.com/user-attachments/assets/a1b40f05-ca96-4bfd-910d-23b7d2f386a1
> Fix crash when trying to open nonexistent folder

- source/funkin/ui/debug/stageeditor/toolboxes/StageEditorCharacterToolbox.hx
- source/funkin/ui/debug/stageeditor/toolboxes/StageEditorDefaultToolbox.hx
- source/funkin/ui/debug/stageeditor/toolboxes/StageEditorObjectAnimsToolbox.hx
- source/funkin/ui/debug/stageeditor/toolboxes/StageEditorObjectGraphicToolbox.hx
- source/funkin/ui/debug/stageeditor/toolboxes/StageEditorObjectPropertiesToolbox.hx
- source/funkin/ui/debug/stageeditor/toolboxes/StageEditorStageToolbox.hx
> [ENHANCEMENT] Stage Editor - Closeable toolboxes

- source/funkin/data/stage/StageData.hx
This caught my eye while I was messing around with stages
> [DOCUMENTATION] The default angle value isn't 1.0 you silly

- source/funkin/ui/freeplay/FreeplayState.hx
N/A
Decided to compile develop on HTML5 on a fine and dandy day and got this error.
> Fix HTML5 compile issue

- source/funkin/play/character/CharacterData.hx
A tiny contribution towards closing #4303
Null safety
> [CHORE] `CharacterData` - Add null safety

- source/funkin/ui/debug/results/DebugTallies.hx
Considering Perfect (Gold) can have separate animations/music, it'd be nice to be able to view those as well for characters that have it.
> [ENHANCEMENT] Add Perfect (Gold) to Results Screen Debug

- source/funkin/ui/debug/charting/commands/CopyItemsCommand.hx
[3796](https://github.com/FunkinCrew/Funkin/issues/3796)
Honestly this was easy as hell i just had to cancel a tween lmao
https://github.com/user-attachments/assets/f906030b-170d-4bea-91d5-6981a9cd5ac7
> [BUGFIX] Fix the Copy Items Notification in Chart Editor having faulty movement when moving the Cursor

- source/funkin/ui/debug/charting/ChartEditorState.hx
Fixes #4523
I did the thing that eric said
~~Who gets the credit, me, eric or both?~~
uhhhhhhhhhhhhhh
> [BUGFIX] Chart Editor - Sort difficulties consistently

- source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx
Fixes #3894
This is moreso a bandaid fix until the file filter stuff actually gets fixed (seems to be a HaxeUI issue??).
> [BUGFIX] Fix FNF legacy files not being able to be opened on mac

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/charting.yml
- .github/ISSUE_TEMPLATE/compiling.yml
- .github/ISSUE_TEMPLATE/crash.yml
Brace yourselves for the wave...
> [GITHUB] Update issue templates for Mobile

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/charting.yml
- .github/ISSUE_TEMPLATE/compiling.yml
- .github/ISSUE_TEMPLATE/crash.yml
- docs/CONTRIBUTING.md
i am funkin on mobile as writing this
> Bump to 0.7.2

- CHANGELOG.md
- hmm.json
- project.hxp
- source/funkin/FunkinMemory.hx
- source/funkin/data/song/importer/FNFLegacyImporter.hx
- source/funkin/data/song/migrator/SongDataMigrator.hx
- source/funkin/graphics/shaders/DropShadowScreenspace.hx
- source/funkin/graphics/shaders/DropShadowShader.hx
- source/funkin/mobile/util/InAppPurchasesUtil.hx
- source/funkin/play/PlayState.hx
- source/funkin/ui/debug/charting/ChartEditorState.hx
- source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx
- source/funkin/ui/mainmenu/MainMenuState.hx
- source/funkin/ui/options/OffsetMenu.hx
> Update main branch to v0.7.3

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/charting.yml
- .github/ISSUE_TEMPLATE/compiling.yml
- .github/ISSUE_TEMPLATE/crash.yml
- docs/CONTRIBUTING.md
- project.hxp
- source/funkin/play/PauseSubState.hx
- source/funkin/ui/options/OffsetMenu.hx
- source/funkin/ui/options/OptionsState.hx
#5423
Fixes #5423, Changes 'INPUT OFFSETS' to 'LAG ADJUSTMENTS' by request of dave.
Also changes the feature to this, AND also also; makes it so if you have the feature disabled, it doesn't show the offsets in the pause menu.
> [BUGFIX + ENHANCEMENT] Offset Menu Adjustments

- CHANGELOG.md
> [DOCS] Tiny Changelog adjustments + credit another contributor

- source/funkin/ui/mainmenu/MainMenuState.hx
For some reason this change from #4787 was lost???? Probably due to a rebase.
> [CHORE] Restore yet another lost change

- source/funkin/ui/debug/stageeditor/handlers/AssetDataHandler.hx
N/A
Changes one line since I forgot that frames can be rotated.
TBA
> [BUGFIX] Fix the Stage Editor's XML Generation not accounting for Rotated Frames

- source/funkin/play/PlayState.hx
Should be a fix for #5430 !!!
Would be epic for the people who are having this notes scrolling issue to try it out see if it does the job well 🙂
> [BUGFIX] Smoother notes scrolling

- hmm.json
https://github.com/FunkinCrew/Funkin/issues/2743
Updated the library reference in hmm.json to point to the commit, which resolved the issue above.
This is the issue since FNF 0.4 (which I also when I noticed the issue first)
> [BUGFIX] Bump thx.core

- source/funkin/ui/freeplay/AlbumRoll.hx
- source/funkin/ui/freeplay/FreeplayState.hx
And *kinda* fix for albumRoll intro animation
> [BUGFIX] Fix for "floaty" albumRoll in FreePlay

- source/funkin/InitState.hx
- source/funkin/play/PlayState.hx
I REALLY hope this WILL be the LAST time we ever see this damn cursed bug
i swear i sprouted some grey hairs strands while trying to figure it out
Anyways, the song restarting bug rn seem to only occur when you're lagging so i added a funni laginator that works by pressing space for who doesn't lag and wanna test this fix
> LAST Fix for the song restarting bug!?!?!?!

- source/funkin/ui/freeplay/FreeplayState.hx
N/A
If you (re-) generated the capsules (either just by entering Freeplay or changing the sorting of songs with Q/E), capsules that should be marked as "new" will not have that symbol until you scrolled directly to the song. This PR fixes it by making the `FreeplaySongData` use the base non-variated song to determine the current variation and then use that variation for other checks like if the song is new. 
https://github.com/user-attachments/assets/b8ffad50-a5ce-4b00-af98-b35505a83623
> [BUGFIX] Fix the `NEW` marking not appearing upon capsule generation

- README.md
> [DOCS] Use game logo from FNF Wiki in README

- source/funkin/ui/freeplay/FreeplayState.hx
#2832
This Pull Requests adds a fade out effect to the song previews in Freeplay, making it sound better when the preview restarts.
https://www.youtube.com/watch?v=zztr7x5WAHQ
> [ENHANCEMENT] Make Freeplay previews fade out before restarting

- source/funkin/ui/debug/charting/components/ChartEditorMeasureTicks.hx
> [BUGFIX] Chart Editor - Update and load the measuring stick

- source/funkin/ui/debug/charting/ChartEditorState.hx
Closes https://github.com/FunkinCrew/Funkin/issues/5725
Commit desc because im too lazy to type it out again
https://github.com/user-attachments/assets/7bb9a463-e5a1-4651-bc40-3d2fa3ec0d5b
> [BUGFIX] Fix the chart editor song playtest behaving like story mode
