assets/images/NOTE_assets.xml

There was an issue related with how the notes were set in the flash xml file. Basically, there's this bug that appears when you hold a note with any of the arrows for a period of time and the camera moves:
These are the trails of the notes that are down the confirm arrows and that in the xml they are set too close of each other, so I tweaked it a little bit by changing some pixels without modifying the origin of the animation too much.

Fixed issue related with arrows and note trails

---

source/PlayState.hx

Fixed a bug that would cause the song to repeat after it ended during the transition. Honestly I can't explain this very well so hopefully this video does a better job.
Note: this bug would sometimes not occur if the game was paused at some point.
https://user-images.githubusercontent.com/24728334/103337172-4a930700-4a2f-11eb-9c68-22427a35b4df.mp4

Added a fix to music restarting when the song ends.

---

source/MainMenuState.hx
source/TitleState.hx

Moving the version check screen to TitleState, allows the game to make early decisions whether to switch to MainMenuState or OutdatedSubState.
Also solves the weird trantition bug.
**Before:**
https://user-images.githubusercontent.com/10368254/103624260-40fc2880-4f74-11eb-856e-d4dd53ca79fe.mp4
**After:**
https://user-images.githubusercontent.com/10368254/103624355-5ec98d80-4f74-11eb-9aee-f44fe5c28cbd.mp4
Let me know if there needs to be a change before merging. Thanks.

Move version check screen to TitleState

---

source/Character.hx

There was an issue where Both bf-christmas and bf-car were resetting their animations too early and were briefly in their idle animations.
Before:
https://user-images.githubusercontent.com/24728334/105255118-d8967500-5b37-11eb-9c07-d08505f312dc.mp4
After:
https://user-images.githubusercontent.com/24728334/105255161-ea781800-5b37-11eb-84b5-d63f73217834.mp4
Edit: sorry if the videos don't load correctly.

Fixed issue with bf-christmas and bf-car resetting animations too early

---

source/NGio.hx

Following the README and using this as the contents for `APIStuff.hx`
```
class APIStuff
{
public static var API:String = "";
public static var EncKey:String = "";
}
```
results in the game quitting due to the invalid API key
lets check if the api key is not empty before creating the core so we don't run into this

check if newgroups api key actually exists before creating core

---

source/ChartingState.hx
source/Conductor.hx
source/MusicBeatState.hx
source/MusicBeatSubstate.hx
source/PlayState.hx
source/Song.hx

Tweaks changeBPM functionality so that the BPM is not reset back to the original after having been changed.
Worth noting is that this may cause inconsistencies with the chart editor, particularly in the function ``recalculateSteps()``.
A potential fix for this could be done by doing this for its for loop instead:
```haxe
var bpm:Int = _song.bpm;
for (i in 0...curSection)
{
steps += 16;
if (_song.notes[i].changeBPM)
bpm = _song.notes[i].bpm;
timeShit += (((60 / bpm) * 1000) / 4) * 16;
}
```
But the chart editor scares me so I do not touch it, not that there are many songs I could test with.

BPM change functionality & implementation

---

source/Note.hx
source/PlayState.hx

Fixes #3. Improves scaling of sustain note trail bits, and clips them off at the middle of the player strums if hit.
A cleaner solution to consider for the future would be to rewrite trails to use a single FlxTiledSprite.

Better sustain note trails

---

source/Note.hx
source/PlayState.hx

oops lol :)
various changes to account for sustain notes no longer being removed on hit that i really should have caught in my original PR
Fixes #424, fixes #432, fixes #429 (the last two technically being duplicates of the first)

Fix oversights causing sustain notes to miss at random

---

source/PlayState.hx

Before, songs without vocals would become desynced whenever the game lagged/stuttered/froze. Now, the notes will stay synced no matter what.

Resync by music instead of vocals

---

source/ChartingState.hx

Remove 2 extra imports, `IOErrorEvent` was imported already.

feat(extra): Remove extra imports

---

source/Discord.hx
source/TitleState.hx

so basically we just add a call to the onExit event and when we exit the game we shut down the discord rpc. Cuz otherwise it doesn't work correctly.

Discord RPC fix

---

README.md

I've been seeing some issues lately relating to how they get an "error" when compiling. When in reality, they're just simple warnings that can easily be ignored
This PR adds a note to the building section telling people to just ignore the deprecated warnings to address the compiling "issues".
I also went ahead and changed formatting for build commands to match `lime test windows -debug`

add notice to build section 

---

LICENSE.md

Self-explanatory, the previous link was incorrect.
|    Before     |     After     |

Fix the `funkin-assets` license link

---

source/funkin/ui/title/TitleState.hx

the tween glitches out when pressing Y multiple times. just cancel the tween if it already exists

FIX WINDOW TWEEN

---

source/funkin/play/notes/Strumline.hx

When hitting a note there is a frame where updateNotes() isn't called.
In most cases this doesn't cause issues but with sustains their length isn't being updated in time causing a visual bug.
https://github.com/FunkinCrew/Funkin/assets/50346006/337d9810-2f1c-449e-8466-99072b65be9e

Fixed an issue where hold note would be invisible for a single frame.

---

source/funkin/ui/mainmenu/MainMenuState.hx

There is this bit of code in the MainMenuState that I assume was supposed to run immediately after changing to the state but instead is run after the transition completes to the state.
This causes the camera to be reset when the transition completes, creating a stutter effect.
I've tested this from multiple scenarios where the state is changed to MainMenuState and nothing seems to break.
_i am not sure why this bit of code exists in the first place actually since the camera reset call made just before it seems to work just fine but idk_
Footage of this problem happening in game (i apologize for the overlapping music i am too tired to rerecord this clip):
https://github.com/FunkinCrew/Funkin/assets/50346006/8ca36750-0ec5-468e-bdce-78bcecf5273e

Fixed stutter once a wipe transition to the Main Menu completes.

---

source/funkin/ui/debug/charting/dialogs/ChartEditorCharacterIconSelectorMenu.hx

This corrects an issue within the character dropdown grid of the chart editor, where the user cannot select them because of the previous hitbox width of the grid. Mention of this bug is found here: #2279 
With this change it makes these characters selectable. No issues known so far

Character selection fix for chart editor

---

source/funkin/ui/transition/LoadingState.hx

I noticed (at least for me) that the loading bar starts from the middle which is probably because previously scale.x was used. And another issue is that it just doesn't move at all.
I fixed this issue by using setGraphicSize and updateHitbox afterwards
I removed the lerp since it made the loading bar look weird

Fix Web Loading Bar

---

source/funkin/play/PlayState.hx

When retrying from the GameOverSubState the current implementation has some issues due to being a sub state now.
This PR attempts to fix those issues.
Things that are altered:
- The "vwoosh" transition is removed from game overs.
- Notes are cleaned before entering the sub state, fixing a flicker effect while the black fade out is playing.
- The health bar (and its icons) no longer lerp back to the default value upon returning to PlayState.
- The score is no longer retained for one frame.
The way this is done is admittedly a little hacky, but is (what i believe to be) the best way around it without making any major alterations to the code. _(Scary)_
I am unsure if the vwoosh transition and the health bar lerp is intended when retrying a song through the GameOverSubState. So those changes …

Polish for the transition from GameOverSubState back into PlayState.

---

source/funkin/graphics/shaders/StrokeShader.hx

Fix a conflict between a shader variable name and a function on some graphics cards.

Fix an AMD shader crash on Freeplay.

---

source/funkin/util/logging/CrashHandler.hx

Another null object reference fix

Fix a crash when querying FlxG.state in the crash handler

---

source/funkin/ui/freeplay/FreeplayState.hx

We were using a broken linear interpolation function to handle the value of the clear percentage (and for that matter the score). This uses the proper `smoothLerp` function which snaps the value once completed.

Fix an issue where the Freeplay menu never displays 100% clear.

---

hmm.json

Currently the game will immediately close after loading on Linux builds, but the newest version of hxCodec fixes this
Should fix #2428

Bump hxCodec commit (fixes Linux issue where it crashes after load)

---

source/funkin/Conductor.hx

This pr only changes some `4`'s inside Conductor to use `Constants.STEPS_PER_BEAT` since `getBeatTimeInMs` uses it but the rest of the functions like `getTimeinSteps` and `getStepTimeInMs` doesn't use it, although its a simple pr it probably helps the reader to understand the `4` inside the functions.

Keep the consistency in Conductor

---

source/funkin/ui/title/AttractState.hx

When pressing any volume key (mute, up or down) the toy commercial closes and was really frustrating

[BUGFIX] Allow Volume Keys while watching Toy Commercial (AttractState)

---

source/funkin/play/GameOverSubState.hx
source/funkin/play/PlayState.hx

Leaving Game Over screen while playtesting from Charting crashed the game.
Also dying when minimal mode crashed.

[BUGFIX] ChartingState GameOver Crashes

---

.github/labeler.yml
.github/workflows/labeler.yml

This should add a github action that automatically labels PR
Currently it:
- Labels `Documentation` to any PRs that change anything in the `docs/` folder, or any `.md` file.
- Labels `Haxe` to any PRs that change `.hx` files
We can do further config as we please, for now I think this one should be enough for the lil prototype 
NOTE: right now this aciton runs on `pull_request`, this is purely for review/testing. After approval, and before merging, we need to change it to `pull_request_target`. See [here](https://github.com/marketplace/actions/labeler#updating-major-version-of-the-labeler)

add simple PR auto labelling action

---

source/funkin/play/PlayState.hx
source/funkin/ui/debug/charting/toolboxes/ChartEditorMetadataToolbox.hx

The Funkin' devs did an oopsie and hardcoded note styles in songs and the chart editor.
- Songs now use the note style provided in the respective variation's metadata file.
- The Note Styles dropdown menu in the Chart Editor now properly populates with entries from the NoteStyleRegistery. (It had a function all along but they forgot to use it lol)
Consired merging https://github.com/FunkinCrew/funkin.assets/pull/8 into the assets repo as it fixes Week 6 Erect songs having the wrong note style as a result of this change.

[FEATURE] Custom Note Style Support

---

source/funkin/play/components/HealthIcon.hx

It allows legacy health icons to have a Winning animation (just if the image has a 3rd frame)
_Boyfriend and Nikusa health icons from FNF: Entity mod_
These have a winning animation in the third image frame (usually any other mod does the same, having the winning animation on the third frame)
https://github.com/FunkinCrew/Funkin/assets/55158797/33acc627-4eb4-4440-a499-2e20fb7a0a4f

[FEATURE] Add Winning support to Legacy Health Icons

---

source/funkin/play/notes/Strumline.hx

Fixes the position of hold notes on downscroll to be on the correct center of the note and strum
| Before  | After |
| ![before](https://github.com/FunkinCrew/Funkin/assets/97055307/4ac48bb6-6131-4165-b997-8943fceab789)  | ![after](https://github.com/FunkinCrew/Funkin/assets/97055307/107c1494-f73d-45e6-b1cd-793f7b40ac3a)  |

Fix hold notes on downscroll

---

source/funkin/ui/transition/LoadingState.hx

hi,
sorry for making another fix for the loading bar. I messed some stuff up.
- I made an oopsie when doing `setGraphicSize`, which lead the loading bar to go back and forth when no callbacks have been finished. The comment in the code explains that part.
- Set the width of the loading bar to 0 at the beginning so that the lerp doesn't start off wrong
I do have a question about the lerp though. Is there a particular reason why we are using `FlxMath.lerp` and using a hardcoded ratio instead of `elapsed`. Another thing i'd like to mention is that the loading bar doesn't reach the end when finishing all callbacks before switching to the next state because the lerp needs to take some time.

[BUGFIX] Fix Web Loading Bar (Again)

---

source/funkin/ui/freeplay/FreeplayState.hx

Caused when the level lists a non-existing song.

[BUGFIX] Freeplay Crash when song is invalid

---

source/funkin/data/BaseRegistry.hx
source/funkin/play/stage/Stage.hx

Before:
```
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: (x: 0 | y: 0 | w: 0 | h: 0 | visible: true | velocity: (x: 0 | y: 0))
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: (x: 0 | y: 0 | w: 0 | h: 0 | visible: true | velocity: (x: 0 | y: 0))
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: (x: 0 | y: 0 | w: 0 | h: 0 | visible: true | velocity: (x: 0 | y: 0))
```
After:
```
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: mainStage
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: mallEvil
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: mallXmas
```

[BUGFIX] Unscripted Stage Log Trace (missing toString for Stage)

---

source/funkin/ui/story/StoryMenuState.hx

When you change difficulty in story mode, score text doesn't update.

Make texts update on difficulty change in Story Menu

---

source/funkin/data/song/importer/FNFLegacyImporter.hx

Before, any legacy imported chart, had `mom` as instrumental suffix (like erect or a variant).

[BUGFIX] Chart Importer Wrong Instrumental

---

source/funkin/ui/title/TitleState.hx

Fixes TitleState in general
- When going back to TitleState, the music gets muted
- Spamming enter when getting to TitleState crashed (wasn't initialized yet)
- No 1 second black screen when going back to TitleState

[BUGFIX] Fix TitleState bugs + crash

---

source/funkin/ui/transition/preload/FunkinPreloader.hx

When running the game from the command line and the current working directory is not the executable's directory the Preloader will fail to find the files it needs, this PR aims to fix this problem. This could perhaps also fix #2444 although it seems to be kinda unrelated.
I know that ideally you'd use `lime run PLATFORM` to run the game without recompiling, but this would not be the case for when downloading the game, specially for Linux players that for whatever reason would like to run it through a terminal without having to change the CWD.
From what I tested it doesn't break anything. Here's a before and after of the problem:
(Before was done in Windows cuz I'm too lazy to recompile, but it should be consistent regardless of the platform) …

[BUGFIX?] Reset CWD before Preloader

---

source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/components/ChartEditorHoldNoteSprite.hx

This pull request fixes two bugs:
| Before                                                                                              |                                                After                                                |
|-----------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------:|
| ![image](https://github.com/FunkinCrew/Funkin/assets/55158797/983d8489-c8c3-441f-9832-ecd9f4617519) | ![image](https://github.com/FunkinCrew/Funkin/assets/55158797/eb06a2d0-f421-4787-b4d1-1fd53e68a145) |
| Before                                                                                    |                                           After …

[BUGFIX] Charting Editor Sustain Trails (2 bugs)

---

source/funkin/play/PlayState.hx
source/funkin/play/event/AdditiveScrollSpeedEvent.hx
source/funkin/play/event/ScrollSpeedEvent.hx
source/funkin/play/notes/Strumline.hx
source/funkin/play/notes/SustainTrail.hx
source/funkin/ui/debug/charting/components/ChartEditorHoldNoteSprite.hx

https://github.com/FunkinCrew/Funkin/assets/107233412/d0626047-9dad-4ac7-8e01-3ced7b20f69f
What this PR does is implement a new event that sets the current scroll speed. As well as a public ``scrollSpeed`` variable in Strumline. Without adding any sustain-related rendering issues.
This PR also adds a ``parentStrumline`` variable to SustainTrail, and a way for it to redraw once the scroll speed changes.
https://github.com/FunkinCrew/Funkin/assets/107233412/8b5fe4d9-e78b-4000-afc0-7cb744b5d234
The event can also affect either strumline, an example of this is the video above!
This event can also set the base scroll directly instead of acting as a multiplier (disabled by default)!
Setting the value to 1 with Absolute disabled will set the speed to the default. (important)
PS; i **ACTUALLY** …

[FEATURE] Scroll Speed Event

---

source/funkin/modding/events/ScriptEvent.hx
source/funkin/play/PlayState.hx
source/funkin/ui/debug/charting/ChartEditorState.hx

Does a couple of things:
- Adds hitDiff to HitNoteScriptEvent
- Adds isComboBreak to HitNoteScriptEvent
- Adds doesNotesplash to HitNoteScriptEvent
- Moved code related to applying the judgement stats (score, health, etc) to a new applyScore function
- popupScore now only has 2 arguments, judgement and combo.
So, why these changes?
popupScore was a bit of a misleading title, as it doesn't just display the judges, but it also applied logic related to them, so I have split the functionality between popupScore and applyScore. This, in my opinion, makes a lot more sense and allows for scripts to display judgements seperately from score application, i.e in the case of mine/hurt notes where maybe they'd want to display a custom judgement to show that you hit a mine. Perhaps …

New judge application logic

---

source/funkin/util/WindowUtil.hx

Fixes the background thingie not being passed properly to the command line due to how Sys works, which causes an error and prevents the link from being opened
~~Could be something with my system for all I know, not sure if being on Ubuntu WSL2 changes how the command behaves.
If anyone else also compiles in Linux (no WSL) please confirm if this error happens to you too.~~
Edit: I tested this through native Ubuntu and also got the same error, so not related to WSL, unless it's related to Ubuntu in general.
Edit 2: This error is caused by how Haxe's Sys.command appends the arguments to the console, encasing them with single quotes. So the original code would cause the command to be `xdg-open 'https:/link.here' '&'` which makes xdg think that & is an argument, so not related to any Linux …

[Linux] Fix "Unexpected argument '&'" error when trying to open URL

---

source/funkin/play/PlayState.hx

Near line 775, originally the trace statements for when there was an error loading a song said "The was an error" instead of "There was an error". This PR fixes these typos.

Fix some PlayState error handling typos

---

docs/COMPILING.md

Moved “download Git” from the middle of the guide to the setup step 
Should prevent errors with Git before installing Git

[DOCS] Make compiling guide more user friendly

---

.github/changed-lines-count-labeler.yml
.github/workflows/labeler.yml

This adds a new step to the Pull Request Labeler workflow, which adds small/medium/large labels to pull requests.

Add change counts labels to Actions labeler

---

docs/COMPILING.md

Due to the recent influx of compiling help issues, I've added a few troubleshooting steps to the Compiling Guide.
This should reduce the amount of work Eric has to do sorting through various compiling help issues.
Any additional troubleshooting steps are appreciated!

[DOCS] Add common troubleshooting steps to compiling guide

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE/bug.md
.github/PULL_REQUEST_TEMPLATE/enhancement.md

This PR should automatically apply the 'status: pending triage' label to every new issue.
Also includes some polish for each issue and PR template.
Question: Should enhancements also automatically receive the 'type: enhancement' label or would you prefer to assign type labels manually?

[DOCS] Automatically assign 'status: pending triage' label to all new issues

---

source/funkin/ui/freeplay/FreeplayState.hx

(I accidentally messed up the previous branch and had to make the PR again. Sorry about that)
Song previews in freeplay will now use the instrumental suffix from the current difficulty's corresponding song variation metadata instead of using the variation id as an instrumental suffix and checking only the "erect" variation.

[BUGFIX] Made freeplay use the metadata to get the instrumental suffix

---

source/funkin/ui/freeplay/FreeplayState.hx

Freeplay tries to access a song's rank using the current difficulty name alone, but custom variation ranks are being saved with a variation prefix. This PR makes freeplay look for the variation prefix when necessary and attaches the associated TODO.

[BUGFIX] Fixed ranks not appearing in freeplay for custom variations

---

source/funkin/play/character/BaseCharacter.hx
source/funkin/play/stage/Bopper.hx

Currently, Funkin directly changes the `x` and `y` properties for offsets. This is a bit tedious because it can break stuff, such as tweens.
This pull request changes the way animation offsets are handled without changing `x`, `y` or `offset`.
Ideally this could be implemented on other classes too.

Better offsets handling for gameplay props.

---

source/funkin/audio/FunkinSound.hx

This should be merged with the changes in [this pr on FlxPartialSound](https://github.com/FunkinCrew/FlxPartialSound/pull/2)

[BUGFIX] Fixed Polymod and Mods Support in FlxPartialSound

---

source/funkin/modding/base/ScriptedFunkinSprite.hx

`ScriptedFunkinSprite.hx` erroneously references `FlxSprite` in the comments. This PR changes it so it properly references `FunkinSprite` instead.

chore: Update ScriptedFunkinSprite.hx

---

CHANGELOG.md

Fixes changelog for the 0.5.0 update!
- Adds Pico (Pico Mix) to the changelog
- Changes 10 Pico Remixes to 11 since Pico (Pico Mix) was forgotten. (Yes, I counted 5 times it is 11 songs)
- Fixed an extra space in Blammed (Pico Mix)
- Re-Explained how to unlock Darnell (BF Mix)
- Added the line where it says new animations have been added for Tankman and Pico

[DOCUMENTATION/BUG-FIX] Fix changelog for v0.5.0

---

README.md

This PR properly adds a link to `credits.json`. Someone made a PR for this at one point (#2325), but it was reverted in #2355 since it was merged into `main` instead of `develop`. It was never merged again to the proper branch, leaving this line unchanged.

chore: Add a link to `credits.json`

---

source/funkin/play/PlayState.hx
source/funkin/play/event/FocusCameraSongEvent.hx

When using Classic on FocusCamera, you have to place any zooms AFTER it, because it breaks them. It also snaps the camera, creating for jerky movement when having to use many Classic camera movements
This fixes that behaviour

fix focuscamera CLASSIC breaking zooms and snapping

---

source/funkin/audio/FunkinSound.hx

fixes `FunkinSound`s being destroyed on `MusicBeatState` state changes regardless of the `persist` property

[BUGFIX] FunkinSound persistence

---

source/funkin/Assets.hx

Closes #3310
This PR adds OpenFL Assets' `getPath()` function to the `Assets` class. This function is really useful for when you need the full file path of something! (Especially when combined with `Paths`)
The before/after images use a test module that retrieves the path of Boyfriend's spritesheet and outputs a message if successful. (See #3310 for reference.)
Before
After

Add `getPath()` to `funkin.Assets`

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/3147,
Changes any instance of screenX/screenY to viewX/viewY as the former is depreciated. Causing the editor to not function due to https://github.com/HaxeFlixel/flixel/pull/3210
Also adds a millisecond part of the playbar :D

[BUGFIX/ENHANCEMENT] Changes instances of FlxG.mouse.screen(x/y) to FlxG.mouse.view(x/y) in ChartEditorState.hx (and more)

---

source/funkin/ui/mainmenu/MainMenuState.hx
source/funkin/util/WindowUtil.hx

Closes #3340
This PR replaces all instances of `CAN_OPEN_LINKS` with `FEATURE_OPEN_URL`. The former was removed and replaced with the latter when the game's project file was switched from `Project.xml` to `project.hxp`, but it seems as if the code wasn't accounted for this change.

Replace instances of `CAN_OPEN_LINKS` with `FEATURE_OPEN_URL`

---

source/funkin/play/notes/StrumlineNote.hx
source/funkin/play/notes/SustainTrail.hx
source/funkin/play/notes/notestyle/NoteStyle.hx

~~#3323~~ (Actually wait only some of the things mentioned there are fixed, only the third bullet and maybe the second one, if you count my duct-tape fix of putting offsets for the hold notes to counteract the offset that I couldn’t find the cause of as an actual fix)
- Made note asset scaling easier to understand. Before, there was some math going on behind the scenes (the hardcoded scaling stuff was probably added before the JSON scaling was implemented), but now, it just uses the scale in the JSON as the scale to apply to the sprites.
- Added offset functionality to the note tail sprites. The attached JSON for the pixel art notes uses this to pretty much fix the tails' offsets.
- In turn, I was able to make the pixel art notes have a scale factor that doesn't have mixels. The tails' …

Fix note and receptor scaling and note tail offsets

---

source/funkin/ui/charSelect/CharSelectSubState.hx

#3156
This PR introduces a new allowInput boolean to CharSelectSubState, false by default and is only set to true when we start playing stayFunky. This prevents the game from being able to run/cancel tweens on a currently null object, being FlxG.sound.music.
https://github.com/user-attachments/assets/faf4bbc3-e1a6-4e28-bd7d-7e002523de97
https://github.com/user-attachments/assets/3d7587ef-781f-4b91-a5eb-93d6ba9cb5d9

[BUGFIX] Disable input in CharSelect until stayFunky plays

---

source/Main.hx

N/A
Fixes a minor bug where the FPS counter object was added regardless of what the Debug Display option was set to.
https://github.com/user-attachments/assets/28119ba4-c710-43c2-870e-96fa8f1271e3

[BUGFIX] Fix bug where FPS counter was always displaying on startup even when disabled

---

source/funkin/play/stage/Stage.hx

N/A
Fixes a call to addCharacter in where if you were to create a custom character in an hscript and then try to add it to the stage, it wouldn't have it's character type get set. Meaning it would not react to any notes being played.
N/A

[BUGFIX] Modding (Polymod): Make addCharacter actually set the characters type

---

source/funkin/Conductor.hx
source/funkin/play/Countdown.hx
source/funkin/play/PlayState.hx

Don't think anyone uses these so no.
Fixes an issue with offsets that would cause it to mass resync vocals, or go forward in time and back really quickly. Causing a lot of artifacts, lagging the game, and being unpleasant.
This also fixes the song starting before the countdown (due to the offset).
This shows blammed at +1 second of instrumental offset.
https://github.com/user-attachments/assets/021e5b06-f67c-491a-8e17-d77bddf9c8be
(2nd clip is accidently the normal version of blammed instead of hard, but the point stands)

[BUGFIX] Chart Editor/Gameplay: Fixes countdown and audio artifacts with offsets

---

source/funkin/data/stage/StageData.hx
source/funkin/play/stage/Stage.hx

Closes #3466
This is a simple PR that adds `flipX` and `flipY` as valid parameters in the stage data. This should be relatively self-explanatory.
Below is a screenshot showcasing an example!

[ENHANCEMENT] Add `flipX` and `flipY` to Stage Props

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/crash.yml
.github/ISSUE_TEMPLATE/enhancement.yml

This PR addresses common points of confusion in bug/crash reports in the following ways:
- Added more guidelines under each section
- Introduced placeholders in text boxes for further guidance
- Made more fields **required** to reduce empty issue submissions
- Added a "Compiled from GitHub Source Code" option under Platforms
- Updated the example Version number to 0.5.0
- Shortened/removed some labels to streamline reviews

Additional Issue Template Improvements

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/crash.yml
.github/ISSUE_TEMPLATE/enhancement.yml
source/funkin/Preferences.hx
source/funkin/save/Save.hx

I came across an instance of [fowl](https://github.com/user-attachments/assets/2fe6fb8f-c2ec-485f-a97e-d02441215012) in the phrase "foul language" so I changed both instances to the correct spelling.
I also fixed a few other lines that caught my eye in Save.hx to make things more consistent.

Fix silly little typo in Preferences and Save

---

source/funkin/ui/charSelect/CharSelectSubState.hx

None as far as I know?
Currently if you hold a key down and press enter on a character in the character select screen, the hold won't stop and the cursor will keep moving.
In some cases this can lead to the current character to be set to an invalid value and the game will crash.
https://github.com/user-attachments/assets/0065b7a7-b98a-4d1d-a3a1-5ef997855f64

[BUGFIX] Stop input spam on character select

---

source/funkin/play/PlayState.hx

This PR fixes a bug where the function onNoteMiss calls applyScore, creating two sets of "000" whenever a note goes off the screen with a combo of 10 or more.
Also removes the "== 0" condition from popUpScore to prevent double displays after Bad or Shit ratings.
Subsequently, this PR removes the "000" display after getting a Bad or Shit rating with a combo of less than 10.
**Question for the devs:** 
Do you intend for the "000" to appear after every Bad and Shit rating regardless of your combo?
**Double combo break display**
https://github.com/FunkinCrew/Funkin/assets/170126004/ccf725f7-0f09-4cfb-af3c-471b7b40ff3b
**Combo break display when combo <10 (bad/shit ratings but not for misses)**
https://github.com/FunkinCrew/Funkin/assets/170126004/292abfda-fd09-4862-ac48-38afb27b5c8f
**Fixed …

Fix duplicate combo counter on combo break

---

source/funkin/play/song/Song.hx
source/funkin/save/Save.hx
source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/freeplay/SongMenuItem.hx

Freeplay would default it's difficulty string to `normal` but pico variations are `normal-pico`, so it wouldn't show you any Pico remix songs until you went to Random and changed difficulties.
This just initializes the suffixed difficulty string with `-pico` (or any other non-bf character id) when we load up Freeplay, so the initial generateSongs() filters correctly

Fix Pico's songs not appearing on Freeplay

---

source/funkin/ui/transition/preload/FunkinPreloader.hx
source/funkin/util/WindowUtil.hx

Just a simple quick and dirty fix to center the "DSP" and "FNF" text in the preloader cuz it bugged me a little...

Center Box Text in Preloader

---

source/funkin/ui/debug/anim/DebugBoundingState.hx
source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/mainmenu/MainMenuState.hx
source/funkin/ui/story/StoryMenuState.hx
source/funkin/ui/title/TitleState.hx

- Fixed an issue where the dialog box wouldn't show up in the animation editor #3151 
- Fixed an issue where the main menu music would cut out when switching menus sometimes #3488

Fix to Character animation editor, plus a main menu music fix

---

source/funkin/ui/charSelect/CharSelectSubState.hx

fixes #3505 
Updating the main cursor to use the `smoothLerp()` instead of `coolLerp()` seems to fix it, as the rest of the squares lerp towards the main yellow cursor.
I believe this bug is caused from the lerp overshooting and needing to recorrect itself using the old lerp method

Fix the character select cursor lerp for lower framerates

---

source/funkin/graphics/FunkinSprite.hx
source/funkin/play/notes/StrumlineNote.hx

[#3571](https://github.com/FunkinCrew/Funkin/issues/3571)
The playStatic function on the StrumlineNote.hx file has this.active = false; which breaks modding compatibility for StrumlineNote sprites with looping animations. By setting this.active = true; it allows StrumlineNote sprites to loop an animation that is defined in the new notestyles folder.
Broken StrumlineNote Animations when playStatic() this.active = false;
https://github.com/user-attachments/assets/30ef10f1-f785-4af3-89d7-383f4285bef4
Working StrumlineNote Animations when setting playStatic() this.active = true;
https://github.com/user-attachments/assets/28ace392-e01f-4d5c-8ef5-ddf1fa00d005
Custom NoteStyle JSON file for reference:

Fixed Conflict With Modded StrumlineNote Sprite Looping Animation

---

source/funkin/ui/freeplay/FreeplayState.hx

[3583](https://github.com/FunkinCrew/Funkin/issues/3583)
Modifies the `changeDiff` function inside `FreeplayState` to account for changing variations.
https://github.com/user-attachments/assets/04ccf4e5-ddea-4ed5-8857-00fd6e643e93

[BUGFIX] Don't restart the FreeplayState song preview when changing the difficulty within the same variation

---

source/funkin/ui/options/FunkinSoundTray.hx

This simple pull request allows for the bars and main soundtray container to be anti-aliased, allowing for a more readable look.
Before
After
Screenshots are in different sizes and do not serve this change justice, but is more noticeable in-game than here.

[BUGFIX/ENHANCEMENT] Fix Soundtray Aliasing / Smoothing

---

source/funkin/ui/options/items/EnumPreferenceItem.hx
source/funkin/ui/options/items/NumberPreferenceItem.hx

fixes #3624
this pr sets `fireInstantly` to true for Enum and Number preference items.
this fixes the issue with the flicker.

[FIX] Remove Flicker When Accepting FPS Setting

---

source/funkin/data/stage/StageData.hx
source/funkin/graphics/shaders/InverseDotsShader.hx
source/funkin/play/stage/Stage.hx
source/funkin/save/Save.hx
source/funkin/ui/debug/DebugMenuSubState.hx
source/funkin/ui/debug/stageeditor/StageEditorObject.hx
source/funkin/ui/debug/stageeditor/StageEditorState.hx
source/funkin/ui/debug/stageeditor/components/AboutDialog.hx
source/funkin/ui/debug/stageeditor/components/BackupAvailableDialog.hx
source/funkin/ui/debug/stageeditor/components/ExitConfirmDialog.hx
source/funkin/ui/debug/stageeditor/components/FindObjDialog.hx
source/funkin/ui/debug/stageeditor/components/LoadFromUrlDialog.hx
source/funkin/ui/debug/stageeditor/components/NewObjDialog.hx
source/funkin/ui/debug/stageeditor/components/UserGuideDialog.hx
source/funkin/ui/debug/stageeditor/components/WelcomeDialog.hx
source/funkin/ui/debug/stageeditor/handlers/AssetDataHandler.hx
source/funkin/ui/debug/stageeditor/handlers/StageDataHandler.hx
source/funkin/ui/debug/stageeditor/handlers/UndoRedoHandler.hx
source/funkin/ui/debug/stageeditor/import.hx
source/funkin/ui/debug/stageeditor/toolboxes/StageEditorCharacterToolbox.hx
source/funkin/ui/debug/stageeditor/toolboxes/StageEditorDefaultToolbox.hx
source/funkin/ui/debug/stageeditor/toolboxes/StageEditorObjectToolbox.hx
source/funkin/ui/debug/stageeditor/toolboxes/StageEditorStageToolbox.hx
source/funkin/ui/title/TitleState.hx
source/funkin/ui/transition/LoadingState.hx
source/funkin/util/FileUtil.hx

N/A
This PR adds a rework/addition of the Stage Editor, nearly identical to the one from the [Stage Editor Engine](https://gamebanana.com/mods/522275), which was also made by me. anysad should be the one with the most familiarity to it, as they have left a suggestion to make it a pull request long time ago.
In comparison to that iteration, this one is modified to support the Stage Format of the Base Game by implementing z-Index support, changing how the animations are handled and so on.
Welcome Dialog:
Main View:
Some of the Dialogs:
If this gets accepted:
1. Haxe-UI Component `.xml` datas for this editor ([link](https://github.com/user-attachments/files/17180202/stage-editor.zip)) would need to be added to `assets/exclude/data/ui`.
2. Stage Files would need to get updated to these …

[ENHANCEMENT] Stage Editor re-work from the ground up

---

cliff.toml

git cliff can nicely generate changelogs for commits written in conventional commit syntax
`fix: fixed boyfriend exploding`
will spit out to 
```md
- Fixed boyfriend exploding
```
I don't think we need to be super strict with making PRs and everyones commits follow along, I've found it pretty straightforward to use conventional commits, as well as rebasing my own and others commits to use conventional commits.

docs(changelog): create a git cliff template for easier changelog stuff

---

hmm.json
project.hxp
source/funkin/save/Save.hx
source/funkin/save/changelog.md
source/funkin/save/migrator/SaveDataMigrator.hx
source/funkin/save/migrator/SaveData_v2_0_0.hx
source/funkin/ui/debug/DebugMenuSubState.hx
source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/stageeditor/StageEditorState.hx
source/funkin/util/SerializerUtil.hx

#3679 
- Replaced all Enum fields with Enum Abstract fields.
- Incremented the Save data version to `2.1.0` (since this is a breaking change) and implemented migration.
- Older versions of the game will now complain that the save data is too new when trying to load.
- Had to create some dummy enums in the save data migrator to prevent errors from loading older saves.
- In the event that the save data fails to parse, the game will now display a big warning popup telling the user to report the issue. It will then create a new save, leaving the broken save in place.

[BUGFIX] Improvements to the save data system to prevent overwriting when resolution fails.

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Adjusts some chart editor movement logic to have a bit more of a polished / smooth experience when moving around the chart editor.
On the todo would be adding a preference of some kind to change the amount of smooth/easing, but this PR can serve as the MVP for chart edit smooth scroll for now!
- uses a smoothLerp() rather than a tween, which it seems like the tween wasn't used all that much anyways
- Essentially ALWAYS smooths out the movement, at least the scrolling
- the api / usage is: change the `currentScrollEase` to set essentially the "target" of where we want to scroll to.
- note: the playbarHead (youtube scrubber type thing at bottom) has to work in a slight different way, since when it gets dragged it's value is updated alongside the drag movement. But it's working all good …

Added smoother scrolling when using the Chart Editor

---

source/funkin/ui/transition/preload/FunkinPreloader.hx

Reverts FunkinCrew/Funkin#2629 as it's not needed anymore due to Lime having patched [this bug internally](https://github.com/openfl/lime/blob/9f369b7637f6f682ffbfb1257ac37435f6dcb820/CHANGELOG.md?plain=1#L73) since 8.1.0

Revert "[BUGFIX] Reset CWD before Preloader"

---

source/funkin/ui/debug/charting/handlers/ChartEditorThemeHandler.hx

What was Eric smoking when he wrote this code??? Anyway, this cleans up some code in the Chart Editor Theme Handler, fixing too few beat/step tick lines appearing on 5/4, 6/4 and 9/8 time signatures.

Clean up a part of ChartEditorThemeHandler, fixing a bug with it.

---

source/funkin/ui/debug/charting/ChartEditorState.hx

my previous smooth scroll implementation seemed to have regressed some functionality with how clicking on the playbar/playhead of the track. This PR re-enables things the old functionality
along with that, also allow for CTRL + mouse wheel to scroll the chart in fine precise increments, which seemed like it was there mostly, but intentionally disabled at some point

fix: re-enable precise chart editor scrolling, and also fix smooth scroll playhead/playbar playback

---

.github/label-actions.yml

* Automatically closes issues as completed when `status: resolved` is added 
* (see https://github.com/FunkinCrew/Funkin/issues/3196#issuecomment-2438656788 and https://github.com/FunkinCrew/Funkin/issues/2214#issuecomment-2417564882)
* Removes every other status label when the `status: duplicate`, `status: rejected`, or `status: resolved` label is applied.
Ideally, Eric should be able to label something as resolved without having to worry about removing the existing status label or manually closing it.
Additionally, we could make it so that every status label removes every other status label when applied, but I'll only make that change if Eric says he prefers it.

Add more functionality to label actions

---

CHANGELOG.md

The older entries in the changelog linked to `ninjamuffin/Funkin`. However, since Funkin was moved to an organization (FunkinCrew), these links lead to nowhere. This PR simply replaces all instances of `ninjamuffin99/Funkin` with `FunkinCrew/Funkin`

chore: Fix a plethora of dead links in the changelog

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/charting.yml
.github/ISSUE_TEMPLATE/crash.yml

I've seen a lot of charting issue reports over the past several months. 
One problem I've noticed is that reporters sometimes describe a charting error without providing directions to find it.
That's why I've decided to create a new issue template that:
* automatically applies the `type: charting issue` label
* includes a required "Location" field
* adapts the existing "Description" field to better suit charting issues
I've also bumped the bug report and crash report templates to 0.5.3

[GITHUB] Create a dedicated charting issue template (and bump version to 0.5.3)

---

source/funkin/util/ReflectUtil.hx

Implements/Fixes #3177
This PR adds a new function to `ReflectUtil`, `setAnonymousField();`. This function is basically a shortcut to `Reflect.setField();`.

[ENHANCEMENT] Add `setAnonymousField();` to `ReflectUtil`

---

source/funkin/util/ReflectUtil.hx

This PR is an extension of #3622 which adds more 3 more functions to `ReflectUtil`: `copyAnonymousFieldOf()`, `deleteAnonymousField()`, and `compareValues()`. These should be relatively self explanatory based on their function names!

[ENHANCEMENT] More `ReflectUtil` additions.

---

source/funkin/input/Controls.hx

#3932 
This PR adds default gamepad binds for freeplay menu
https://github.com/user-attachments/assets/25700a39-47ee-4974-9806-76c58a68cb8b

[ENHANCEMENT] Set Default Gamepad Controls for Freeplay Menu

---

source/funkin/modding/IScriptedClass.hx
source/funkin/modding/events/ScriptEvent.hx
source/funkin/modding/events/ScriptEventDispatcher.hx
source/funkin/modding/events/ScriptEventType.hx
source/funkin/modding/module/Module.hx
source/funkin/ui/MusicBeatState.hx
source/funkin/ui/MusicBeatSubState.hx

This PR adds callbacks to Modules for when the game loses/gains focus. Mods can use these callbacks like so:
```haxe
import funkin.modding.module.Module;
/**
* A test of the focus events.
*
* Delete this later.
*/
class FocusTest extends Module {
public function new() {
super('FocusTest');
}
function onFocusLost(event) {
trace("LOST FOCUS!");
}
function onFocusGained(event) {
trace("FOCUS GAINED!");
}
}
```
- The game fires the `FOCUS_LOST` event when the game is closed/exited, though I'm pretty sure this is a Flixel bug since the events ride off of Flixel's existing `onFocus()` and `onFocusLost()` functions. (You're closing the game anyway though, so it's not much of an issue.)
- Should `onFocusGained()` be `onFocus()` instead? I'm not really sure.

[ENHANCEMENT] Add Script Events for losing/gaining focus

---

source/funkin/util/ReflectUtil.hx

#3622 broke compilation on the `develop` branch since `setAnonymousField();` was returning `Dynamic` instead of `Void`
My bad

Quick `develop` branch compilation fix

---

source/funkin/ui/options/PreferencesMenu.hx

* This PR will close https://github.com/FunkinCrew/Funkin/issues/3021
* This PR adds the missing descriptions for each of the options,
* This PR updates the already pre-existing descriptions to be more... understandable ig?
* This PR updates the camera deadzone so that when you scrolled down to the next option, it won't have as much as not needed space as before.
https://github.com/user-attachments/assets/086cde79-df60-4d9b-aa3b-2fcd66059c70

[ENHANCEMENT] Preference Descriptions + Other Tweaks

---

source/funkin/util/Constants.hx

Currently, there's no real way to detect whether or not the game is a debug build in HScript (`MacroUtil` doesn't work, so does basically anything that involves getting compiler defines), you COULD do something like this:
```haxe
function isDebugBuild():Bool {
return Constants.versionSuffix == ' PROTOTYPE';
}
```
However, this is unreliable since V-Slice forks can change the version suffix.
This PR adds a new boolean to `Constants`, `DEBUG_BUILD`. Which is basically self-explanatory, `false` if it's a release build, and `true` if it's debug (has the `FEATURE_DEBUG_FUNCTIONS` compiler flag).

[ENHANCEMENT] Add `DEBUG_BUILD` to `Constants`.

---

source/funkin/InitState.hx

https://github.com/FunkinCrew/Funkin/issues/3879
https://github.com/FunkinCrew/Funkin/issues/3712
- The mouse cursor is no longer visible outside of ingame editors
Before:
After:
https://github.com/user-attachments/assets/625af0c6-3d0a-4b27-b94a-6128d321eef6

[BUGFIX] Mouse cursor is no longer visible outside of the ingame editors

---

source/funkin/save/Save.hx

This PR fixes an early return in `hasBeatenSong()` and replaces it with `continue;` instead (since it's a `for` loop). There's already a `return false;` below the loop in the event that the song hasn't been beaten.

[BUGFIX] Fix early return in `hasBeatenSong()`

---

source/funkin/play/song/Song.hx

[3856](https://github.com/FunkinCrew/Funkin/issues/3856)
For some reason when building the voice group in `Song`, whether or not the vocal files existed wasn't checked, which this PR aims to fix. 
Before:
https://github.com/user-attachments/assets/4152f062-c0ad-4855-960a-7971fc05c4b6
After:
https://github.com/user-attachments/assets/810f87e9-78f0-42de-a43d-a94ebd19d5a4
(please ignore there being wrong icons in the footage that's just a side effect of a thing im working on)

[BUGFIX] Prevent constant Vocal Resyncs on Inst-only songs

---

.github/label-actions.yml

GitHub Actions will now auto-close issues when assigned the `status: stale` label.
Also:
- adds the new `status: resolved internally` label into every unlabel list. Originally from (https://github.com/FunkinCrew/Funkin/pull/3919)
- no longer auto-closes `status: duplicate` issues due to GitHub's new close reason.

[GITHUB] Auto-close issues with the `status: stale` label

---

.github/changed-lines-count-labeler.yml

This is an associated PR for the GitHub label cleanup proposal I'm currently working on.
> [!NOTE]
> Refer to https://github.com/FunkinCrew/Funkin/issues/3920 for the full label project.
For this part of the label cleanup, please change the names of the three size labels in the following way:
| Label | New Name |
| `small` | `size: small` |
| `medium` | `size: medium` |
| `large` | `size: large` |
This change will help organize the [full list of labels](https://github.com/FunkinCrew/Funkin/labels) alphabetically and make it easier to use.

[GITHUB] Change size label names in PR labeler

---

README.md

Removes link to Contributor's Guide because we don't have one.
Replaces it with links to the [Issues](https://github.com/FunkinCrew/Funkin/issues) page and [Pull requests](https://github.com/FunkinCrew/Funkin/pulls) page!

[DOCS] Update Contributing section in README

---

.github/labeler.yml

This PR changes the PR labeler workflow to account for the changes made in #3920.
- Changed `Documentation` and `Haxe` to `pr: documentation` and `pr: haxe` respectively.
- Added a new function for the new `pr: github` label. This label gets applied if a user either modifies a `.yml` file, or modifies any file in the `.github` folder.

[GITHUB] Changes to the PR labeler workflow

---

source/funkin/input/Controls.hx

Closes #3026 
- Reordered UI Controls from `UP`, `LEFT`, `RIGHT`, `DOWN` to `LEFT`,  `DOWN`,  `UP`,  `RIGHT`,

Change UI Controls Order

---

source/funkin/util/ReflectUtil.hx

This PR adds the remaining missing functions to `ReflectUtil`. This should hopefully complete the class and give scripts access to every function in `Reflect` that isn't harmful or malicious.

[ENHANCEMENT] EVEN MORE `ReflectUtil` additions.

---

.github/label-actions.yml

GitHub Actions will now unlabel `status: needs r&d` when an auto-closing status label is applied.
Also removes `close reason` lines from PRs since PRs don't have close reasons.

[GITHUB] Add `status: needs r&d` label to label actions

---

.github/labeler.yml

[GITHUB] Add `status: pending triage` to all PRs

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/charting.yml
.github/ISSUE_TEMPLATE/compiling.yml
.github/ISSUE_TEMPLATE/crash.yml
.github/ISSUE_TEMPLATE/enhancement.yml

- Adds a link to the [Issues Guide](https://github.com/FunkinCrew/Funkin/issues/4050) to all 5 issue templates.
- Includes links to the [Compiling Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) and [Troubleshooting Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/TROUBLESHOOTING.md) in the compiling help template.
- Adds a `Console Output` field to the compiling help template.

[GITHUB] Add Links to Guides in Issue Templates

---

docs/CONTRIBUTING.md

Closes https://github.com/FunkinCrew/Funkin/issues/2362
This is a general contributor's guide made in collaboration with @Hundrec, serving as a resource for people wanting to contribute to the repository!
~~Since this is still in somewhat-early stages, this PR has been opened as a draft as a means to gather feedback from the community.~~
~~Please let me know your thoughts on this!~~
UPDATE: This PR is no longer a draft.

[DOCS] Contributor's guide

---

docs/TROUBLESHOOTING.md

Adds the explanation from [this comment](https://github.com/FunkinCrew/Funkin/issues/4111#issuecomment-2644033905) to the Troubleshooting Guide.
* Clarifies that warnings and deprecated functions can be safely ignored.
* Instructs user to type y when encountering the hxcpp prompt.
* Adjusts formatting for consistency

[DOCS] Add more console outputs to Troubleshooting Guide

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/charting.yml
.github/ISSUE_TEMPLATE/compiling.yml
.github/ISSUE_TEMPLATE/crash.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/pull_request_template.md
README.md

Links README and Issue Templates to [CONTRIBUTING.md](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md)

[DOCS + GITHUB] Add CONTRIBUTING.md links to README and Issue Templates

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/charting.yml
.github/ISSUE_TEMPLATE/compiling.yml
.github/ISSUE_TEMPLATE/crash.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/pull_request_template.md
README.md
docs/CONTRIBUTING.md
docs/TROUBLESHOOTING.md

- `Contributor's guide` (#4133)
- `Add more console outputs to Troubleshooting Guide` (#4115)

chore: Merge `main` to `develop`

---

docs/Funkin' Debug Hotkeys.md

After checking the docs and `MainMenuState.hx`, I noticed only one of the 7 hotkeys is listed, so there is the list updated

[DOCS] Added missing debug hotkeys

---

source/funkin/data/song/SongRegistry.hx
source/funkin/data/stage/StageRegistry.hx
source/funkin/modding/PolymodHandler.hx
source/funkin/play/ResultScore.hx
source/funkin/play/ResultState.hx
source/funkin/play/notes/SustainTrail.hx
source/funkin/play/notes/notestyle/NoteStyle.hx
source/funkin/ui/options/PreferencesMenu.hx
source/funkin/ui/story/LevelTitle.hx

A few files in the `source` folder do not follow [the code style](https://github.com/FunkinCrew/Funkin/blob/main/CODESTYLE.md), namely formatting. This PR fixes up the formatting for these files, making them consistent with the rest of the source code.

chore: Fix the formatting on a few files

---

source/funkin/play/stage/Stage.hx

When referring to `FlxSprite`s in the comments, it's usually written as "an FlxSprite". 
However, `Stage.hx` is the ONLY file to refer to `FlxSprite`s as "a FlxSprite".
Literally fucking unplayable.
This PR fixes this grave mistake, making the game playable again. :)
(This PR also serves as a test to see if label actions are working properly again!)

chore: Fix an inconsistency in one of the comments for `Stage.hx`

---

source/funkin/ui/title/TitleState.hx

This code was used at one point during the Week 7 update, but now has been obsoleted by `AttractState`.

[CLEANUP] Removed unused code from `TitleState`

---

docs/CONTRIBUTING.md

Closes #4152 
Thanks @Lasercar!
Implements a dropdown Table of Contents to the Contributing Guide.

[DOCS] Table of Contents for CONTRIBUTING.md

---

source/funkin/modding/PolymodHandler.hx

Reverts FunkinCrew/Funkin#3607
The `FunkinTypeResolver` class was removed in the `develop` branch, so there's no need for this blacklist anymore.

Revert "chore: Blacklist an additional class in Polymod."

---

source/funkin/ui/charSelect/CharSelectSubState.hx

Fixes #3747
`CharSelectSubState` never actually checked to see if the playable character was unlocked before pushing them to `nonLocks` (to play the unlock animation). The only thing it did was check to see if the playable character ID was in `Save.instance.charactersSeen`, if it wasn't, it would be pushed to `nonLocks` and still play the unlock animation despite never actually unlocking them.
This, in turn, basically unlocked Pico right from the get-go if you entered the Character Select screen early, whether it be through a modded Playable Character, or the Debug Menu.
Now, Pico remains locked (since WeekEnd 1 was never beaten), while Madoka (a modded playable character) is unlocked.

[BUGFIX] Actually check if the Playable Character is unlocked

---

source/funkin/Preferences.hx
source/funkin/save/Save.hx
source/funkin/ui/options/PreferencesMenu.hx

Implements/Fixes #2386
This PR adds an option that allows FNF to launch the game in fullscreen automatically. This saves the hassle of pressing the fullscreen hotkey everytime you open the game.
Tested on both desktop and web.

[ENHANCEMENT] Add an option to launch the game in fullscreen

---

source/funkin/play/ResultState.hx

Closes #2283
Just one simple line change to move the mask shader more to the left.

[BUGFIX] Fix the difficulty graphic cutoff in the Results Screen

---

source/funkin/modding/PolymodHandler.hx

`openfl.net.SharedObject` just has a [`resolveClass` function](https://github.com/openfl/openfl/blob/9f0b2d66712b58c5cd28523c3e05ce8026ea9642/src/openfl/net/SharedObject.hx#L962C1-L995C3) lying around for some reason. This PR blacklists the class so scripts can't use it.

Blacklist `openfl.net.SharedObject` from scripts

---

source/funkin/ui/freeplay/CapsuleOptionsMenu.hx

Fixes #3562
`CapsuleOptionsMenu` has its own method of handling inputs, independent of `FreeplayState`. This, in turn, meant that inputs were still enabled even AFTER selecting a song.
This PR adds a Boolean called `busy`. This pretty much acts the same as the one in `FreeplayState`.
This is *sort of* a janky solution, but you can't really do anything much on the Freeplay side since `busy` is enabled to prevent `FreeplayState` from accepting inputs while the Instrumental Selector is open (unless you like... made a new boolean to check if the instrumental selector is open or something lol).
The arrows in the Instrumental Selector (`InstrumentalSelector`) can still be controlled, however, this is purely a visual thing.
I tried tackling the issue before opening this PR, but I couldn't really …

[BUGFIX] Fix the instrumental selector being spammable

---

source/funkin/input/Controls.hx
source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/options/ControlsMenu.hx

Inspired by [this comment from Eric](https://github.com/FunkinCrew/Funkin/issues/3034#issuecomment-2364762699), HOME and END now jump to the top and bottom of the Freeplay menu respectively.
https://github.com/user-attachments/assets/82cf062e-5641-4bfb-b51d-45a074410e63
If you have better names for the controls please let me know.

[ENHANCEMENT] Faster scrolling in Freeplay

---

docs/COMPILING.md
docs/TROUBLESHOOTING.md

This should help Linux users with some issues they might find.

[DOCS] Some extra Linux troubleshooting

---

CHANGELOG.md

Makes *many* changes to polish and streamline the changelog.
* Changes the tense of all verbs to be consistent from 0.5.3 to 0.3.0
* Rewords most "Fixed" entries to improve readability by reducing repetition ("Fixed an issue where...")
* Reorders entries to be roughly grouped with related entries
* Combines two entries into one in 0.5.3
* Removes an extra PR link in 0.5.2
* Links missing PRs
* Reorders first-time contributors by PR # 
* Adds line breaks to match Keep A Changelog's format
* Credits Matriculaso instead of gamerbross upon [gamerbross' request](https://github.com/FunkinCrew/Funkin/pull/2684)
* Replaces JustKolosaki with KoloInDaCrib
* Fixes at least two typos

[DOCS] Changelog Overhaul

---

CHANGELOG.md

Makes some changes on top of #4296 to polish the Changelog.
* Correctly list all new contributors since 0.3.3. Quadruple-checked for good measure.
* Removes entries related to Documentation and GitHub changes
* Standardizes punctuation
* Rewords a few more entries for clarity
* Fixes a few more spelling and grammatical errors
* Separates versions by three line breaks to reduce visual clutter

[DOCS] Correctly list all new contributors in Changelog + polish

---

docs/Funkin' Debug Hotkeys.md

No, but it (Hopefully) prevents one from being opened in the future!
The debug hotkeys documentation was still missing a few keys. 
This PR adds them to the documentation. Also removes the current 3 keys under the freeplay state since they're not debug keys.
https://github.com/FunkinCrew/Funkin/pull/4213/files?short_path=737fecf#diff-737fecf79d99f06956475861d2dc4e995dd59c2be3c0edaf12163941d250a7a7

Add remaining debug keys

---

source/funkin/play/PlayState.hx

Fixes #4304 
Once vocals are done their time gets set to a negative value, which triggers `resyncVocals`. This is especially present when songs bf songs use their pico remix counterparts' instrumentals, which are typically longer than the original instrumental. This PR aims to prevent `resyncVocals` being called upon the aforementioned circumstance by putting a check to see if the time of vocals is negative.
https://github.com/user-attachments/assets/243e1479-0574-4c1d-b5ce-65accb25babe

[BUGFIX] Prevent the song being incompletable if the inst is longer than vocals

---

source/funkin/play/PlayState.hx

Fixes #4304, (finally) fixes #3142
https://github.com/FunkinCrew/Funkin/pull/4309#issuecomment-2727275864
> @Hundrec 
>
> Has found _the_ way to replicate the bug - when the song ends, click off the window, then click back into it - what ends up happening is that you bypass music's oncomplete function (because the music still plays even when you've clicked off) and so, the song doesn't end.
This also means that once the music playing when unfocused haxe issue is fixed, it should fix this issue too (but then again, maybe keep this in just in case it's also caused by something else?).

End the funking song I'm going insane

---

CHANGELOG.md

* Removes entries that weren't included in 0.6.0 (Pico Good Results easter egg + some `accepted` PRs)
* Adjusts new contributors section to account for removed entries
* Moves the 0.6.0 new contributors section to the bottom of 0.6.0
* Makes minor edits to a few entries for accuracy and clarity
* Makes all spacing consistent

[DOCS] Remove 0.6.0 Changelog entries that weren't implemented + polish

---

docs/Funkin' Debug Hotkeys.md

No
https://github.com/FunkinCrew/Funkin/commit/afb4a3dd6856ecdbbe5daf76d644cc4e9d420edf
https://github.com/FunkinCrew/Funkin/blob/00cdac7dc80fe91451077cea5ef25c3c0f065924/docs/Funkin'%20Debug%20Hotkeys.md
Note, this is is to be merged onto main because the merge of the secret repo into the public one ruined all the documentation/github stuff on the develop branch (unless that's intended so it's easier to merge, then carry on).

[DOCS] Remove removed debug keys

---

source/funkin/modding/module/Module.hx

I noticed only 2 of the event functions had documentation while the rest didn't, this PR adds documentation for the rest of the functions.

[DOCS] Add missing documentation to `Module`

---

docs/CONTRIBUTING.md

On April 22nd, 2025, we began enforcing a new [Maintenance Policy](https://github.com/FunkinCrew/Funkin/discussions/4782) for PRs! This PR updates the Contributor's Guide to reflect the new policy, expanding `Merge conflicts and rebasing` into a `Maintaining your pull request` section.

[DOCS] Contributor's Guide Maintenance Policy

---

CHANGELOG.md

_Reopening of #4847_
* Added some more notable entries to the **Fixed** section of 0.6.3
* Updated some 0.6.3 and 0.6.0 PR commit links to lead to commits in the Funkin' repo history (rather than commits on no branch)
* Removed a scoring rebalance entry that didn't actually get implemented
* Reworded a few entries for clarity
* Removed a few extra spaces

[DOCS] Additional 0.6.3 Changelog bugfix entries + updated commit links

---

project.hxp

Removes `CHANGELOG.md` from project.hxp
Eric mentioned potentially excluding the Changelog from the game files since it keeps getting revised after updates are released.
Perhaps we could find a better way to direct players to the latest Changelog.

Remove Changelog from game files

---

CHANGELOG.md

My Pull Request was used on April 4th, to add the ability to skip the Eggnog Erect cutscene which can now be seen as of `0.6.3`
(Reopened due to me being told to put it on main.)

[DOCS] Update CHANGELOG.MD to include my pull request.

---

source/Main.hx
source/funkin/Preferences.hx
source/funkin/save/Save.hx

Fixes #4803
The vsync mode enum was directly saved into the save data and caused it to break like the last time this was done (not that I was around when that happened) so I've instead changed it to save as a string.
Also fixes the save data loading twice by only calling preferences _after_ the save is loaded.
[Nah.](https://wiki.teamfortress.com/w/images/b/b2/Engineer_no02.wav)
Original PR here: https://github.com/FunkinCrew/Funkin/pull/4823

[BIGFIX] Fix Options not loading from Save Data

---

source/funkin/play/PlayState.hx
source/funkin/play/ResultState.hx
source/funkin/play/components/ClearPercentCounter.hx
source/funkin/play/scoring/Scoring.hx
source/funkin/ui/freeplay/FreeplayState.hx

Fixes #4824
Misses now actually make you miss your grade, and dropping sustain notes early no longer adds to the miss tally.
https://github.com/user-attachments/assets/dad46208-ee60-4d15-8fda-79034de61b45

[BUGFIX] Fix scoring changes

---

source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx

Fixes #3111
The chart editor would always end up adding the default difficulty to the metadata if it wasn't already there.
Now, not only does it set the selected difficulty when a song is loaded to the first available difficulty, it also only adds a difficulty to the metadata if the one that's selected when the song is saved doesn't exist in it.

Chart editor - Don't add default difficulty to song metadata

---

source/funkin/ui/freeplay/FreeplayState.hx

Fixes #4856 and #4858.
I put the fixes for these together because the fix for the second issue doesn't work without the fix for the first. (Well it technically does, but it introduces another bug)
When switching to Erect difficulty while the Random capsule is selected, the selected song would change to Bopeebo Erect. This happens because the new functionality added for switching variations when a song doesn't have it doesn't check if the song is null (aka random). This causes it to execute the code to switch the selected song to the closest one that does have that variation, Bopeebo. I fixed this issue by making the game check if the song is null too before attempting to select a different song.
The second issue is when you leave Freeplay with the Random capsule selected, the difficulty …

[BUGFIX] Fix two issues with the Random Capsule in Freeplay

---

source/funkin/api/newgrounds/Medals.hx

It fixes this issue (not my screenshot but posted somewhere on the VSlice network server)
it hasn't been reported yet afaik
The `medalJSON` array is never null, so it never gets populated properly. This pr changes the check to if the length is 0.

[BUGFIX] Fix Medals being granted sometimes crashing the game

---

source/funkin/play/PlayState.hx

unsure, attempted to find any but couldn't.
If you loaded a song that had no characters and attempted to restart the song, it would crash due to the game attempting to initialize a health icon of a non-existent character. This resolves that issue by adding a null check before attempting to re-initialize the health icon.

[BUGFIX] Avoid crash when restarting song without characters.

---

source/funkin/play/PlayState.hx

Fixes #4764 
Made it so that the game runs a `performCleanup` call before reloading the state. This also kills off any running dialogue. 
https://github.com/user-attachments/assets/af8b1719-7347-4140-adcb-4f7b3c1b340e
Note that the HaxeFlixel icons appearing is a separate issue.

[BUGFIX] Prevent the game from Crashing when Hot-Reloading during Dialogue

---

source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx

Fixes #2468 
When accessing the current chart's song metadata it creates a blank variation if the currently selected one doesn't exist. This could cause a crash when accessing that variation's sound data.
This makes it so it checks if the current selected variation exists before trying to load the song, and sets it to the default one if it doesn't exist. Though I think a proper fix would be for the aforementioned behavior to not happen, but this will work for now.
https://github.com/user-attachments/assets/65ae2c8c-6c1f-4ab8-995a-36643b8f7ea4

[BUGFIX] Prevent chart editor from loading invalid variation

---

source/funkin/util/MemoryUtil.hx

No
Previously when generating the crash log, `cpp.vm.Gc.memInfo()` was used which returns a 32bit integer that overflows after ~2.14GB. Ez fix by just using `memInfo64` instead
Before, memory overflows after ~2.14GB
After, no overflow! Memory can grow as much as it wants! Hooray!

Fix memory overflow in crash log

---

source/funkin/ui/freeplay/FreeplayScore.hx

Fixes #2318 
The last digit of the FreeplayScore doesn't get cleared before it sets a new number.
https://github.com/user-attachments/assets/bd2cd058-8754-47cb-a888-264ed1ba06da
I uhhhhh think I understand how the code for the FreeplayScore now? I spent way too much time staring at the code trying to figure out how it works (and where I could set the intendedscore to 1M to test the fix), like a few hours. Ah well, I fixed it in the end, didn't I?
Ok, let's try that again, this time without accidentally starting the new branch from another fix.

FreeplayScore seventh/million number not being cleared fix

---

source/funkin/ui/freeplay/FreeplayState.hx

fixes #2944 
Add an additional check before running the onConfirm logic that checks for if the menu is already doing something, i.e is busy, which would be set to true since the exit logic happens before the accept logic. Exit logic already had this check so no idea why accept logic didn't lol

[BUGFIX] Prevent pressing Back and Accept keybinds on the same frame in FreeplayState causing a crash

---

source/funkin/input/Controls.hx

Fixes #4354 
When attempting to retrieve for a button name it could try to access a non-existent value from an empty set of inputs, causing a `Null Object Reference` error.
This changes so it falls back to `N/A` when there's no inputs available.

[BUGFIX] Fallback when no defined inputs

---

source/funkin/data/song/SongRegistry.hx
source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/freeplay/FreeplayState.hx

[3661](https://github.com/FunkinCrew/Funkin/issues/3661) [3762](https://github.com/FunkinCrew/Funkin/issues/3762)
Up until this point, the Freeplay Menu's `Random` button was only able to cycle to default difficulties (easy, normal, hard). This PR makes it so that it checks for all the songs loaded, makes an array for all the available difficulties per character, and goes through a for-loop to fill it up. That way it also accounts for Pico not having Erect/Nightmare songs and doesn't switch to those difficulties.
https://github.com/user-attachments/assets/d137f910-4789-41d7-9c1a-4eab27226b47

[BUGFIX] Fix the `Random` Button in FreeplayState not being able to switch to Erect/Nightmare songs

---

.gitmodules
CHANGELOG.md
docs/COMPILING_MAC.md
source/funkin/api/newgrounds/Events.hx
source/funkin/api/newgrounds/Leaderboards.hx
source/funkin/api/newgrounds/Medals.hx
source/funkin/audio/visualize/ABotVis.hx
source/funkin/graphics/adobeanimate/FlxAtlasSprite.hx
source/funkin/modding/module/Module.hx
source/funkin/play/PlayState.hx
source/funkin/play/ResultScore.hx
source/funkin/play/ResultState.hx
source/funkin/play/character/CharacterData.hx
source/funkin/save/Save.hx
source/funkin/ui/PixelatedIcon.hx
source/funkin/ui/charSelect/CharSelectGF.hx
source/funkin/ui/charSelect/CharSelectSubState.hx
source/funkin/ui/debug/results/ResultsDebugSubState.hx
source/funkin/ui/freeplay/FreeplayDJ.hx
source/funkin/ui/freeplay/FreeplayScore.hx
source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/options/PreferencesMenu.hx
source/funkin/ui/title/TitleState.hx
source/funkin/ui/transition/LoadingState.hx
source/funkin/ui/transition/StickerSubState.hx

[3631](https://github.com/FunkinCrew/Funkin/issues/3631)
No, this does not cap the score itself as well. Just wanted to clarify that.
Caps the score displays in `ResultState` and `FreeplayState` to their maximum possible value. Adding more numbers instead would just make it look ugly and yucky :[
(this is not as massive of a change as it shows lol it makes it look like the automatically made spaces from vscode settings are one of the changes lol)

[FIX] Cap Score Displays to their biggest possible values

---

source/funkin/data/DefaultRegistryImpl.hx
source/funkin/data/IRegistryEntry.hx
source/funkin/data/dialogue/conversation/ConversationRegistry.hx
source/funkin/data/dialogue/dialoguebox/DialogueBoxRegistry.hx
source/funkin/data/dialogue/speaker/SpeakerRegistry.hx
source/funkin/data/freeplay/album/AlbumRegistry.hx
source/funkin/data/freeplay/player/PlayerRegistry.hx
source/funkin/data/freeplay/style/FreeplayStyleRegistry.hx
source/funkin/data/notestyle/NoteStyleRegistry.hx
source/funkin/data/song/SongRegistry.hx
source/funkin/data/stage/StageRegistry.hx
source/funkin/data/story/level/LevelRegistry.hx
source/funkin/play/cutscene/dialogue/Conversation.hx
source/funkin/play/cutscene/dialogue/DialogueBox.hx
source/funkin/play/cutscene/dialogue/Speaker.hx
source/funkin/play/notes/notestyle/NoteStyle.hx
source/funkin/play/song/Song.hx
source/funkin/play/stage/Stage.hx
source/funkin/ui/freeplay/Album.hx
source/funkin/ui/freeplay/charselect/PlayableCharacter.hx
source/funkin/ui/story/Level.hx
source/funkin/util/macro/RegistryMacro.hx
source/funkin/util/macro/SingletonMacro.hx
source/funkin/util/tools/ISingleton.hx

This pr adds a macro for registries and entries. This macro adds default implementations for registries and entries.
Currently we need to implement the `DefaultRegistryImpl` individually for each registry because of the `@:generic` metadata that BaseRegistry has.

[FEATURE] Registry Macro

---

source/funkin/util/tools/SongEventDataArrayTools.hx

Fixes #4722 
`SongEventDataArrayTools` only checked for the time when searching for the index of an event, which caused a deleted event's sprite to not get killed since the editor would think another event with the same time was the event that got deleted.
This adds an extra check to ensure it's actually the same event. For some reason this was previously only done for notes.
[!rest is a secret I start to believe it](https://github.com/user-attachments/assets/540294f3-7a6e-4ba7-bdfb-a2660ced46c2)

[BUGFIX] Fix removal of stacked events

---

source/funkin/ui/options/OptionsState.hx

Closes #4702 
`enabled = (prompt == null);` is the fix. I <3 easy fixes
https://github.com/user-attachments/assets/668a8063-68c6-4c39-a15b-8c146ba36a9e

[BUGFIX] Disable Movement in OptionsState when the Clear Save Data prompt is active

---

source/funkin/play/PauseSubState.hx

Closes #4552
Swaps the positions of "Restart Dialogue" and "Skip Dialogue" in the pause menu to be consistent with the order for cutscenes.
Before:
After:

Change order of Restart and Skip in Dialogue pause menu

---

source/funkin/ui/freeplay/CapsuleOptionsMenu.hx
source/funkin/ui/freeplay/CapsuleText.hx
source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/freeplay/LetterSort.hx
source/funkin/ui/freeplay/SongMenuItem.hx

Fixes #3190, fixes #3627, fixes #3703, fixes #3890, fixes #2351
This PR fixes ~~seven~~ six issues:
1. The letters not ~~looping their animation and~~ restarting their animation when selected
2. Lettersort input not being disabled when a capsule is opened
3. The first rank of a song overriding itself
4. The instrument selector using the capsule's current position rather than the position the capsule is targeting
5. A null reference fix for when the instrumental selector is exited while a timer for the arrows is still running 
6. ~~The remembered difficulty being set to constants.DEFAULT_DIFFICULTY when random is selected rather than only using it as a fallback.~~
The random capsule jumping into it's position.
Also, if the capsule has a null target song or difficulty, it now also …

Freeplay UI fixes

---

source/funkin/ui/freeplay/FreeplayState.hx

No, but I did mention this issue here: https://github.com/FunkinCrew/Funkin/issues/4856#issuecomment-2837162544
Based on the comment in the code, when changing filters, the game should land on the song you had currently selected if it is still in the list. Otherwise, it should land on the first song in the group (or the random capsule if there are no songs in the group). This isn't what actually happens though. If the song you had selected previously isn't in the list, it will switch to the random capsule. If you had the random capsule selected, it will switch to the first song in the list (if there are songs in the list).
This happens because the code uses a variable `curSong` defined in the callback for changing filters and checks if it is null to determine if it is still in the list. …

[BUGFIX] Fix the Behavior of Selected Song when Changing Filters in Freeplay

---

source/funkin/play/PlayState.hx

No, and I don't think anyone would unless they looked at the code to notice this.
According to line 949 in `PlayState.hx`, there is a 1/1000 chance to use a special pause menu. The function used to calculate this chance is `FlxG.random.bool`. This function takes in a number to use as a percent chance for something to happen (ex: passing in 50 would give it a 50% chance to return `true`). 
The number currently passed into this function to determine the chance of getting the special pause menu is 1 / 1000. This wouldn't give you a 1/1000 chance as it was not converted to a percent for the function first. This value would need to be multiplied by 100. You can see that this was done correctly in `GameOverSubState.hx` line 223 for the 1/4096 chance of getting the fakeout death animation:
``` …
```

[BUGFIX] Fix the chance of getting the special pause menu

---

source/funkin/ui/freeplay/FreeplayState.hx

Whoops, I didn't know there were _two_ settings of the `intendedCompletion`
And this is why we test PRs/the develop branch

[BUGFIX] Fix `Fix scoring changes`

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Fixes #2614 
The chart editor would always break after returning from PlayState when either changing window size or going fullscreen. This was caused by the UI camera not updating (probably because it is killed), so this fixes it by simply manually updating it.
~~Not me taking many hours trying to fix something I thought was HaxeUI's fault~~
https://github.com/user-attachments/assets/47c66298-ae10-4925-bb0d-f484645bde12

[BUGFIX] Chart Editor - Fix resolution breaking after returning from PlayState

---

source/funkin/ui/debug/anim/DebugBoundingState.hx

- This PR aims to fix an issue with the `Animation Editor` whenever a person tried to save offsets for the character, which didn't have the filename, thus making people write it themselves, which can be very annoying if you are making a mod with hundreds of characters.
**BEFORE / AFTER:**
https://github.com/user-attachments/assets/3921d47e-1d39-4b8c-83b4-5782cb55e053

[BUGFIX] Animation Editor not saving the file name

---

source/funkin/ui/mainmenu/MainMenuState.hx

Fixes #4179
Title. It's literally because the freeplay state is opened as a substate and therefore doesn't call startExitState, which updates the rememberedSelectedIndex.
This PR simply adds that line into the freeplay menu item callback function.

Main menu not remembering freeplay menu selection fix

---

source/funkin/util/plugins/VolumePlugin.hx

Fixes #4616
The volume plugin doesn't have a destroy function.
No

[BUGFIX] Destroy the volume plugin when wiping save data

---

CHANGELOG.md

The commit from #4901 got lost, so the changelog on the develop branch is messed up again. I also added a couple entries that I noticed in the changelog on `main` which were missing from the one on `develop`.

Fix the Changelog on the develop branch again

---

source/funkin/graphics/adobeanimate/FlxAtlasSprite.hx

Fixes #4475, fixes #4472, fixes #4614
It's literally one line.
Credit to @KoloInDaCrib for finding the issue
https://github.com/user-attachments/assets/97a9ae7b-4227-4e62-851f-2d499c9c5b44

[BUGFIX] Fix texture atlas sprites looping infinitely

---

source/funkin/ui/debug/charting/dialogs/ChartEditorWelcomeDialog.hx

#4802 
This pr prevents a game crash when you quickly open a recent .fnfc chart before the tooltip for the recent link appears.
This is solved by simply just hiding the link before the entire welcome dialog is hidden so the tooltip doesn't try showing up at all after you click on the link.
https://github.com/user-attachments/assets/cef72b1a-f34b-40d6-91dc-e6124950a361
https://github.com/user-attachments/assets/0dcf304b-9b01-4624-9b04-09da47dc45e7

[BUGFIX] Prevent the game from crashing when clicking a recent chart before tooltip shows up

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/charting.yml
.github/ISSUE_TEMPLATE/compiling.yml
.github/ISSUE_TEMPLATE/crash.yml
docs/CONTRIBUTING.md

Bumps templates and docs to 0.6.4 in preparation for the update.

Bump Repo Versions to 0.6.4

---

.github/changed-lines-count-labeler.yml

Adds two new size labels to the PR labeling workflow:
* `size: tiny` for changes of **4** lines or less
* `size: huge` for changes of **500** lines or more

[GITHUB] More PR size labels

---

.github/changed-lines-count-labeler.yml

With the introduction of `size: tiny` and `size: huge`, each label's threshold has been adjusted by a bit.
This PR ensures the labeler adheres to the new boundaries!

[GITHUB] Adjust PR size labeler thresholds

---

source/funkin/play/PauseSubState.hx
source/funkin/play/PlayState.hx

Closes https://github.com/FunkinCrew/Funkin/issues/2879 and #3600.
Scripts like `spookyMansion.hxc`, `phillyTrain.hxc` (and Erect versions) play sound effects that don't pause with the game.
Philly's train sound does get paused although that's done manually through the stage script.
This is based on how PlayState handles pausing of camera tweens.
https://github.com/user-attachments/assets/1b234058-feb0-4577-95f2-4284c8ec09cd

Make sound effects pause with the game

---

source/funkin/api/discord/DiscordClient.hx

These traces would flood the console, which would make finding certain logs harder. This PR simply removes them.

Remove spammy traces from `DiscordClient`

---

source/funkin/play/PlayState.hx

Fixes #4822, fixes https://github.com/FunkinCrew/Funkin/issues/4892, fixes #5047 
##
This is basically @KoloInDaCrib's PR #4825 redone with his permission. His commit was cherry-picked so he'll still get credit for some of the changes.
This is caused by the vwooshTimer recently implemented, because the game simultaneously runs updating for both the timer and the countdown, causing the countdowns to be stackable.
~~Right now I've made it so that nothing can update while the timer is active, let me know if that should be changed.~~
New Author's note: This is not the case anymore.
https://private-user-images.githubusercontent.com/67389779/437747749-be4ad467-dc8e-4976-89e1-9fb598de6086.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50 …

[BUGFIX] Fix Countdown Stacking upon Restarting

---

source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx

Fix #4947
A fix for my other PR. Use the first available difficulty as a fallback if the currently selected one cannot be found.
https://github.com/user-attachments/assets/d3ba1303-3439-4e36-90cd-2b9b29291e81

[BUGFIX] Chart editor - Use first difficulty only as fallback

---

source/funkin/play/PlayState.hx

Fixes #4955
`GitarooPause` state only saved current song's id, current variation and current difficulty, nothing else. This PR fixes that by using `lastParams` as the construction parameter.
https://github.com/user-attachments/assets/0864e0b4-c6de-4a6c-9550-ecb34eca6c80

[BUGFIX] Fix the Gitaroo Man Easter Egg screen not saving all PlayState Parameters

---

source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/components/ChartEditorHoldNoteSprite.hx

#4120 
Essentially copied some code from the regular notes and applied it to note trails
https://github.com/user-attachments/assets/3afc1ef0-1e50-4810-9620-9e337868f0e6

[BUGFIX] Move the Note Trails when moving a Held Note in the Chart Editor

---

source/funkin/api/newgrounds/Leaderboards.hx

Changes expected song id at Leaderboards API to match with the assets song id
Closes https://github.com/FunkinCrew/Funkin/issues/4527
Changes the expected song id to match with the assets Lit Up Songs (BF Mix included)
https://github.com/user-attachments/assets/9b9de769-1fbb-43ab-825a-e115c3f06a53

Fix Lit Up being impossible to submit score into

---

source/funkin/ui/title/TitleState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/4433
Hides the debug cursor when the Title Screen starts up using the same line of code as #3881.
In 0.6.2, loading into the Title Screen while the game is unfocused keeps the debug cursor visible after clicking back into focus.
#3881 intended to fix this issue, but only ended up removing the debug cursor flickering in the top left for a split second.
Both that change and this one are necessary to make the debug cursor never show up during launch, focused or unfocused.

[BUGFIX] Hide debug cursor when Title Screen starts

---

source/funkin/api/discord/DiscordClient.hx
source/funkin/api/newgrounds/Leaderboards.hx
source/funkin/api/newgrounds/Medals.hx
source/funkin/api/newgrounds/NewgroundsClient.hx
source/funkin/modding/PolymodHandler.hx

Closes #4996 
Closes #4997
Closes #4998
Adds sandboxes for following API Classes: 
* `NewgroundsClient`
* `Medals`
* `Leaderboards`
* `DiscordClient`
The newgrounds class sandboxes only provide getter support, and DiscordClientSandbox provides support for setting the status and shutting it down. Let me know if you think the masses crave for something more.

[ENHANCEMENT] Sandboxed API Classes

---

source/funkin/ui/freeplay/FreeplayState.hx

No, but it prevents one from being opened in the future!
You no longer have to enter a song first to open the chart editor on that song, you can instead open it directly from in the freeplay state.
~~I would also like to make it actually choose a random song when opening on random, as atm it opens a blank song.~~ Done!
https://github.com/user-attachments/assets/671adcd8-8d3f-41ea-b1e6-ecdb2638e18f

Open chart editor on selected song in freeplay state

---

source/funkin/play/PlayState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/4990
`instance` gets set to `null` in `performCleanup()` when the game hot-reloads, this was caused by https://github.com/FunkinCrew/Funkin/pull/4769.
This led to multiple errors from scripts that tried to access `instance`, and eventually a crash from line 1882 from `DiscordClient`.
This PR sets `instance` back to `this`, fixing the errors and the aforementioned crash.

[BUGFIX] Fix the game crashing when hot-reloading with F5

---

source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/freeplay/SongMenuItem.hx

Fixes #5063
Fixes two issues caused by my freeplay UI fixes
1. The song text clips into the rank area when rank smashing.
2. The old rank not being smashed into oblivion (though previously it always smashed itself, then with the fixes, nothing).
Higher rank replacing lower rank:
https://github.com/user-attachments/assets/0886f5a0-c5da-4c07-aca9-73355ae67489
No rank to rank:
https://github.com/user-attachments/assets/7cfb745d-db21-494d-83e1-8958f5f3c828

[BUGFIX] Freeplay menu - New rank doesn't SMASH old rank

---

source/funkin/ui/freeplay/FreeplayState.hx

(Redo of #4449)
Closes #4429
Now displays the "Press [ KEY ] to change characters" message if more than one character is unlocked (instead of only when a new character is available)

[ENHANCEMENT] Always display charSelectHint after unlocking character

---

source/funkin/modding/PolymodHandler.hx

N/A
Not only it has `CompiledClassList` from which you can retrieve `sys` and Newgrounds classes, it has nothing of use to mods.
Credits to @KoloInDaCrib for discovering the security vulnerability.
Delightfully Devilish Script Example:
```haxe
var classLists = [
CompiledClassList.get("package~funkin.api.newgrounds~recursive"),
CompiledClassList.get("package~sys~recursive")
];
for (list in classLists)
{
for (class in list)
{
var className = Reflect.getClassName(class);
if (className == "sys.io.Process")
{
var proc = new class('echo "HELLO WORLD" > FUCKKKKK');
proc.close();
}
if (className == "funkin.api.newgrounds.Medals")
{
class.awardStoryLevel('weekend1');
}
}
}
```
N/A

Vulnerability Patch: Blacklist `funkin.util.macro.*`

---

source/funkin/ui/debug/charting/ChartEditorState.hx

(Redo of #4711)
Fixes #4713 
Prevents the playhead from disappearing above or below the grid when the playhead isn't in its default position
https://github.com/user-attachments/assets/3b105a33-7101-482f-ae38-4f918cc1bb9b
Please let me know if there's a better way (or place) to do this!
I also need some more playtesting on this to ensure everything works. Any help is appreciated :)

[BUGFIX] Prevent Chart Editor playhead from scrolling before song start

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Fixes #4256
The Chart Editor playbar timer will now display the correct number of milliseconds when below 100 ms.
https://github.com/user-attachments/assets/4c6ae17a-2c2a-4234-bfe5-12bcf8f318bf

[BUGFIX] Fix Chart Editor playbar millisecond display

---

source/funkin/ui/debug/charting/ChartEditorState.hx

No, but it prevents one from being opened in the future!
Ctrl clicking on a hold note causes a null reference error because it tries to check if a regular note is selected, rather than a hold note.
This simply changes it to check for a hold note instead.

Chart editor - ctrl click on hold note null reference fix

---

source/funkin/ui/MenuList.hx
source/funkin/ui/mainmenu/MainMenuState.hx

Fixes #2438
When the debug menu is opened, it doesn't check if the menu is busy (aka about to call a state change) and cancel the currently flickering menu to stop the state change.
This PR simply changes it to do that.

Main menu - Cancel state change on debug menu open

---

source/funkin/ui/debug/latency/LatencyState.hx

Fixes the NOR in #4252 (please make two different things two separate issues ok thx)
The `close` function was never being called by anything so in some cases `cleanup` would never run and cause an error.
But `destroy` on the other hand can be relied on, so this fixes this by simply replacing `close` with it.
(Not sure why someone would run hot-reload in the input offsets state though... oh wait, this also happens if you press F4 since there's also a state switch, so valid issue I guess)
N/A ~guhh i can't be bothered to make a video for this fix~

[BUGFIX] Fix LatencyState cleanup not being performed in hot-reload

---

source/funkin/ui/title/TitleState.hx

Closes #5159 
This fixes a crash when spamming or holding d or i on title state before the outline shader is called.
https://github.com/user-attachments/assets/7d96d5d0-c86e-46c8-ad19-cf3e35a2d4ac
https://github.com/user-attachments/assets/8f07f841-aa98-4301-8417-24b137a6b67d

[BUGFIX] Fix TitleState Shader Crash

---

source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/freeplay/SongMenuItem.hx

Fixes #4876. Fixes #2659.
When switching song lists (changing filters or difficulties) from a song not in the new list, its text would remain highlighted when you switched back to the list it is in. This PR fixes the issue by setting the `selected` value of the capsule to `false` before the song list might change.
I also made an adjustment in `SongMenuItem.hx` to fix the squashed text. A detailed description of the change is in a comment below.
Video of song text not being highlighted:
https://github.com/user-attachments/assets/cd647ce0-f5e1-4034-9aae-8198eb12759d
After the 0.6.4 update, there were three scenarios I found that would always result in a capsule having squished text which is shown below:
https://github.com/user-attachments/assets/9141f79a-1276-48a3-bf75-4cede81fb4e3
Here, …

[BUGFIX] Fix Two Issues With Song Text on Freeplay Capsules

---

source/funkin/ui/debug/stageeditor/StageEditorState.hx

_Non existent_
Only one exit confirmation can now be opened when pressing the exit hotkey.
Also plays the music properly so the conductor uses the bpm of the music.
https://github.com/user-attachments/assets/83ef29b4-4488-4045-8d6b-f8af749811d5
https://github.com/user-attachments/assets/c9f1f475-1470-46fd-b99c-e97ce32dc787

[BUGFIX] Stage Editor - Are you sure?

---

source/funkin/ui/freeplay/FreeplayState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/5244 (and technically https://github.com/FunkinCrew/Funkin/issues/5243)
Fixes https://github.com/FunkinCrew/Funkin/issues/5242
Exiting from the Character Select Screen tweens everything from `exitMoversCharSel` back into their original y positions, however this never accounts for tweens of other visual elements like the `albumRoll` or `charSelectHint`, causing `albumRoll` to repeatedly update its exitMovers and `charSelectHint` to be above the viewing field.
https://github.com/user-attachments/assets/f0f8a091-43ec-4283-94b7-522fac3ac689

[BUGFIX] Fix exiting from Character Select Screen causing issues with Visuals in FreeplayState

---

.vscode/settings.json
source/funkin/InitState.hx
source/funkin/ui/debug/stageeditor/StageEditorState.hx

Closes #4811, fixes #4808
Ctrl+N -> new stage dialog
Also adds windows target configuration preset for straight to stage editor (and the stage _builder_ too). 
Also also makes the stage editor exit to the _main_ menu, like every other editor.
Also also also changes the exit hotkey to Ctrl + Q (and the text), to match the chart editor.
https://github.com/user-attachments/assets/63e1d6bc-113f-43b2-8643-120227526c3a

[ENHANCEMENT] Stage Editor - New stage keybind + exit hotkey change + Stage Editor/Builder build presets

---

source/funkin/modding/module/Module.hx

Comments in Module.hx incorrectly refer to `Pause on Unfocus` as `Auto Pause` even after the option was renamed, so this PR fixes that.

[CHORE] "Auto Pause" -> "Pause on Unfocus" in Module.hx comments

---

source/funkin/play/ResultState.hx

Fixes #2851
When the ratings finish popping in, it plays the new highscore animation, even though it's already played by a timer when the state is created.
I can't be bothered, it's such a tiny issue and I know this fixes it.

New highscore plays twice fix

---

source/funkin/ui/freeplay/FreeplayState.hx

Fixes #5246
When you enter freeplay from character select, `onDJIntroDone` is called immediately, but it's also still called by the dj when they finish their intro animation.
https://github.com/user-attachments/assets/63d511c1-2991-4c3a-8d2a-5b2b9ea40c2d

[BUGFIX] Freeplay - Intro callback running twice fix

---

source/funkin/ui/debug/DebugMenuSubState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/5252
Every time an editor is entered, a styleSheet "user" is created, which persists throughout the entire play session. This PR removes that styleSheet so that a new one is generated upon entering any editor.
https://github.com/user-attachments/assets/77f51e93-403d-4b69-b984-8b72c02937a7

[BUGFIX] Fix Chart Editor's Playbar using incorrect Style Data when switching Editors

---

source/funkin/ui/freeplay/Album.hx
source/funkin/ui/freeplay/AlbumRoll.hx
source/funkin/ui/freeplay/BGScrollingText.hx
source/funkin/ui/freeplay/CapsuleOptionsMenu.hx
source/funkin/ui/freeplay/CapsuleText.hx
source/funkin/ui/freeplay/DifficultyStars.hx
source/funkin/ui/freeplay/FreeplayDJ.hx
source/funkin/ui/freeplay/FreeplayFlames.hx
source/funkin/ui/freeplay/FreeplayScore.hx
source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/freeplay/FreeplayStyle.hx

Contribution towards https://github.com/FunkinCrew/Funkin/issues/4303
This PR adds null-safety to the following classes:
* `funkin.ui.freeplay.Album`
* `funkin.ui.freeplay.AlbumRoll`
* `funkin.ui.freeplay.BGScrollingText`
* `funkin.ui.freeplay.CapsuleOptionsMenu.InstrumentalSelector`
* `funkin.ui.freeplay.CapsuleText` (*PARTIAL*)
* `funkin.ui.freeplay.DifficultyStars`
* `funkin.ui.freeplay.FreeplayDJ`
* `funkin.ui.freeplay.FreeplayFlames`
* `funkin.ui.freeplay.FreeplayScore`
* `funkin.ui.freeplay.FreeplayScore.ScoreNum`
* `funkin.ui.freeplay.FreeplayState.DifficultySelector` 
* `funkin.ui.freeplay.FreeplayState.FreeplaySongData`
* `funkin.ui.freeplay.FreeplayState.DifficultySprite`
* `funkin.ui.freeplay.FreeplayStyle`

[CHORE] Null safety to 14 `ui.freeplay` classes

---

source/funkin/ui/AtlasText.hx

A tiny contribution towards closing https://github.com/FunkinCrew/Funkin/issues/4303
Null safety

[CHORE] `AtlasText` - Add null safety

---

source/funkin/api/newgrounds/Leaderboards.hx
source/funkin/api/newgrounds/Medals.hx

A tiny contribution towards #4303.
Seems like it wasn't implemented in these classes because of a compile error when retrieving values from the internal maps.
Turns out there's no need to iterate through the lists, you can just `@:privateAccess` them, and since both `Medal` and `Leaderboard` are just abstracts over integers the internal map type is compatible with them, which allows you to just return them directly.
> [!NOTE]
> ~`_map` itself and the rest of the Newgrounds API isn't null-safe so this might still cause a Null Object Reference error if either the medals or leader boards aren't fully loaded.~ I've made it fallback to an empty map just in case so this might not be a problem anymore.

chore: Add null-safety to `Leaderboards` and `Medals`

---

source/funkin/ui/debug/results/DebugTallies.hx

Fixes #4951.
Turns out that the new scoring changes broke the ranks on the test result screen...
This fixes it by adding 60 notes to the sick count and 9 notes to the good count on each debug ranking. Can be fixed by zero-ing the missed notes too but then no funny number.
https://github.com/user-attachments/assets/b46f7dbb-99f2-4daa-af72-da264cd8e2b4

[BUGFIX] Fix Debug Results not showing correct rank

---

source/funkin/play/PlayState.hx

* https://github.com/FunkinCrew/Funkin/pull/4701 PR forgot to remove the unnecessary comments that were present in `PlayState.hx` related to ComboMilestone!
* In order to NOT confuse someone going through the source code, it would be better to remove them.

[CHORE] Remove comments related to `ComboMilestone`

---

source/funkin/ui/freeplay/FreeplayState.hx

Fixes #4415
Switching to Erect difficulty and back removes the rank letter display on some songs. This is caused by the song list not being updated correctly when the difficulty is changed, resulting in some of the songs losing their rank display when their capsules are refreshed.
I added in a call to the `generateSongList` function inside the `changeDiff` function to refresh the song list for the currently selected difficulty and variation (if the song list has changed) before all of the capsules are refreshed.
Update: Because of the new changes with the jump-in animation, I added a default parameter to `generateSongList` so this animation doesn't happen twice.
Before:
https://github.com/user-attachments/assets/674ca32b-1c5f-4568-a935-f897f708af73 …

[BUGFIX] Ensure Rank Display stays after changing variations

---

source/funkin/util/logging/AnsiTrace.hx

easiest fucking line change of my life lol
for context:
```
[USER]@[REDACTED]s-MacBook-Air lol % $TERM
zsh: command not found: xterm-256color
```
ansitrace was directly checking if it was simply `xterm` instead of if it started with `xterm`

Check if TERM starts with `xterm`

---

source/funkin/data/song/SongData.hx
source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx

Fixes #4859 1/2
Imagine never actually setting the charter in the new or clone functions of the SongMetadata class.
> [!IMPORTANT]
> Requires https://github.com/FunkinCrew/funkin.assets/pull/172
> I also noticed that there's no charter value for the add variation dialog.
Next time, I'll make day one PRs like this targeted towards the develop branch and keep them as drafts until develop is updated.

[BUGFIX] Fix Charter field not being set in song metadata

---

source/funkin/ui/credits/CreditsState.hx

this pr changes the behaviour of the credits line, to not be all created at the beginning, but rather that they get recycled once a new line appears on the screen.
this should improve memory usage, especially when backers entries are supported

Recycle Credit Lines

---

source/funkin/play/notes/NoteHoldCover.hx

This fixes [Issue #3772](https://github.com/FunkinCrew/Funkin/issues/3772)
I was able to fix this while adding hold covers to DnB 3.5 so I thought I'd submit a PR fixing it here.
Essentially, sometimes if you drop a hold note, and then you hit one right after (from my friends and I's experience, the hold note has to be RIGHT after the dropped one), the one you just hit doesn't give a cover. 
This bug happens periodically, (which is why I say _sometimes_), from my experience it takes a couple tries to get it but when you do end up getting it the first time it happens all the time.
I tested it with Lit Up (BF Mix) and Bopeebo since it was most easily debuggable, and it didn't appear to happen anymore.
**BEFORE (Bug happens at 0:15):** …

Fix a bug where holding down a note after dropping the previous one would sometimes make its cover over not show.

---

source/funkin/play/ResultState.hx

Currently, only `animatealtas` objects for the `ResultState` have the priviledge of having a script class support. This PR gives `sparrow` objects the love they deserve, even if they aren't used that much :]

[ENHANCEMENT] [MODDING] Scripted Class support for Sparrow Results Objects

---

source/funkin/play/GameOverSubState.hx

Fixes #4637
When a death quote finishes playing, the `startDeathMusic` function call in `confirmDeath` somehow also affects `deathQuoteSound`, giving it the same values as `gameOverMusic`. Because `deathQuoteSound` is now not null, the game stops it, but this stops `gameOverMusic` too as they had the same values.
This PR fixes this issue by calling `startDeathMusic` after the death quote is checked for and stopped.
Before:
https://github.com/user-attachments/assets/dece1cf8-4c85-46d8-b6b5-21a1946d3e20
After:
https://github.com/user-attachments/assets/ad795090-60ba-4afe-8a15-14200a730465

[BUGFIX] Fix Retry Sound after Death Quote finishes

---

source/funkin/play/PlayState.hx

Fixes #5277 
View title
https://github.com/user-attachments/assets/3ece1a4b-33bb-4f07-87f7-fd7e11a36215

[BUGFIX] Cancel Tweens and Timers upon exiting PlayState

---

source/funkin/ui/debug/charting/contextmenus/ChartEditorSelectionContextMenu.hx

No, but it prevents one from being opened in the future!
The flip and selection buttons were broken (they aren't set up in the class for the selection context menu). This PR fixes that.
~~Can someone please tell me why there's a button to select everything in the selection context menu????~~

[BUGFIX] Chart Editor - Selection context menu fix

---

source/funkin/ui/freeplay/FreeplayState.hx

For some reason there's this useless boolean in Freeplay?? It doesn't do anything so this PR removes it.

[CLEANUP] Remove unused code from `FreeplayState`

---

source/funkin/Conductor.hx
source/funkin/util/TimerUtil.hx

qol class for a making batches of flxtimers, so you can do stuff like
```haxe
new Sequence([
{time: 1, callback: some_func},
{time: 2.5, callback: () -> {
some_var = true;
}}
], Conductor.beatLengthMs / 1000);
```
instead of
```haxe
new FlxTimer().start(1 * (Conductor.beatLengthMs / 1000), some_func);
new FlxTimer().start(2.5 * (Conductor.beatLengthMs / 1000), () -> {
some_var = true;
});
```

[ENHANCEMENT] timer sequence

---

hmm.json

This version of Polymod includes the following:
- Allow accessing static fields of other scripted classes.
- NOTE: Pending merge of larsiusprime/polymod#194 You can't import scripts with a different `package`, they have to have matching packages for now.
- Added support for variables with getters and setters.
- Added support for defining enums in scripts.
- ~~Partial~~ **FULL** support for abstracts. You can finally use FlxColor properly!
- Note that you can't access instance methods of abstracts directly, but you can still use them by calling the static method and passing the instance as the first argument.
- Added support for aliased imports (`import funkin.graphics.FunkinSprite as Sprite;`)
- Fixed try-catch blocks being pretty much completely broken (the catch block will run if …

Experimental Polymod

---

source/funkin/FunkinMemory.hx

Just clear sound asset keys from the sounds map instead of textures, not sure if this was causing any real world issue *but* it seems like it would be good to properly clear everything anyways.

Clear key from correct map

---

source/funkin/ui/title/TitleState.hx

Closes #5349 
My first mobile PR :D and I guess the second ever public mobile PR.
Just a lil' QOL change I suggested that's easily replaceable by an in-game Exit button that I decided to do anyway.
~TODO: There appears to be a small issue where you may have to touch on it more than once for it to work for some reason.~
Turns out that it's 'cause `justPressed` doesn't work too well in this case. Managed to fix it by replacing with `justReleased`.
https://github.com/user-attachments/assets/f55c4129-0edc-47c9-ad9c-947c4d82f5cc

[ENHANCEMENT] Make Android Back button close the game in Title screen

---

source/funkin/ui/freeplay/FreeplayState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/5398
Recent update made it so that `changeDiff` wasn't being called when controls aren't active.....however upon state init, controls are set to inactive, meaning that `changeDiff` wasn't being called for state initialization, which means that upon entering into freeplay, many things tied to the difficulty but most noticably the difficulty stars didn't get updated.
https://github.com/user-attachments/assets/a193c952-9d2b-41dc-8fb5-3fe813db65e8

[BUGFIX] Fix the Freeplay Difficulty Stars not showing up correctly upon song completion

---

source/funkin/ui/options/PreferencesMenu.hx

I couldn't find any issues about this bug.
There's a bug where if you exit the preferences menu, the position of the camera resets when you reenter it. This causes the camera to be in its default position even if the selected preference item is at the way bottom.
Before:
https://github.com/user-attachments/assets/26a33d88-dd13-4fd7-93fb-554fb29fa1fb
After:
https://github.com/user-attachments/assets/f73868f0-bd45-4da2-88cd-116e7bbf37e3
As you can see in the before, the camera position isn't right when you reenter the preferences menu as it should be positioned near the bottom where the selected preference item was. The after video shows exactly how it should look after reentering the preferences menu.

[BUGFIX] Fix Preferences Camera Position Upon Enter

---

source/funkin/play/PlayState.hx

Fixes #5371
I've realized the train sounds on Philly Train stages were broken, sometimes working, sometimes not. Turns out it was because the stages reuse the sound, and the sounds pause system was destroying it. I had failed to notice this when I originally coded this system lol. So this makes it so the sounds are only destroyed if they also auto-destroy.
~I feel like this might solve #5371 although I'm not really able to reproduce it on the `develop` branch, though I did seem to experience the same bug on Philly Erect (thought that was apparently because of an oversight when I was coding this PR where I was stopping the auto-destroying sounds and not the other way around lel)~
~I don't think a video would suffice~

[BUGFIX] Only destroy paused sounds on restart if they have `autoDestroy` enabled

---

source/funkin/data/song/SongData.hx
source/funkin/save/Save.hx
source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/components/ChartEditorNoteSprite.hx

Closes https://github.com/FunkinCrew/Funkin/issues/5271
Adds a new toggle under `View`, `Note Kind Indicator` which is on by default. With this enabled, notes with custom notekinds will have a little star next to them to separate them from the normal notes. To add to this change, I added tooltip support for notes so that the user knows exactly which notekind the note is (tooltip is disabled if the note is the of the default kind.)
https://github.com/user-attachments/assets/78a2173d-71e9-438f-83f2-09039cfb171e

[ENHANCEMENT] Display an Indicator for Note Kinds in Chart Editor

---

source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/story/StoryMenuState.hx

I checked, couldn't find anything.
What this PR adds is a quick camera fade that occurs after selecting a song in freeplay or selecting a week in the story menu. This makes it a way better transition from the menu you're in to the actual game, rather than the menu freezing for a few seconds just for it to immediately switch to the game. I also tested this on web and it looks good.
Freeplay:
https://github.com/user-attachments/assets/52fd7d06-5a15-4727-a58c-de01b31cdf2d
Story Menu:
https://github.com/user-attachments/assets/e040b01b-c13b-485f-8219-9fca8aedc5ae

[Enhancement] Add Camera Fade To Selecting Songs and Weeks

---

source/funkin/play/PlayState.hx

Fixes #3168
Fixes #2385
In Blazin', whenever you press the reset button and the pause button at the same time (press reset first), you'll experience the death animation, but instead how it looks in the screenshot below. This was fixed by checking if the player isn't dead when trying to pausing.

[BUGFIX] Fix Blazin' Death When Pressing Reset and Pause Button

---

source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/handlers/ChartEditorAudioHandler.hx

Fixes #3041, fixes #3463
When a variation is loaded (or an audiotrack is reloaded), the new audiotracks don't have their playback speed set. 
This PR fixes that, by doing after they're loaded.
Volume resets to 100% after playtest. 
The volume sliders use values of 100 and isn't divided down to a single float, so it'd always be set to 100% after a playtest or a different audio track being loaded.

[BUGFIXES] Chart editor - Set playspeed after variation load, volumes being reset to 100%

---

source/funkin/ui/title/TitleState.hx

No
The title menu only worked with the start button on a gamepad, which is ok, but too many people would try to use the South button, notice that it doesn't work, and end up confused. This PR makes it so both the Start and South buttons work
https://github.com/user-attachments/assets/79cd266c-d5a5-4129-b985-7bfec49365db

[ENHANCEMENT] Make both Start and Accept buttons work on Title Menu

---

source/funkin/play/GameOverSubState.hx
source/funkin/play/GitarooPause.hx
source/funkin/play/PlayState.hx
source/funkin/play/components/HealthIcon.hx
source/funkin/play/notes/Strumline.hx
source/funkin/ui/transition/LoadingState.hx

A quite large contribution towards #4303.
~This still needs a bit of polishing so I'm making this a draft for the moment.~ I think I'm satisfied with how it turned out.
I've also included `LoadingState` here as it made sense for me since it's responsible for switching the game to the `PlayState`.
`PlayState` might've been the most troublesome class to add null-safety to since it has so many fields and whatnot. It isn't complete null-safety since ~some fields still need to be initialized later in `create` and also the fact~ the null-safety checker has many oddities. But some notes regarding it:
* I've made it so `currentSong` **cannot** be null at all, so there's gonna be errors thrown in the case something may set it null.
* I added a new optional parameter to Strumline's constructor, …

[CHORE] Add null-safety to `PlayState` and `LoadingState`

---

source/funkin/FunkinMemory.hx
source/funkin/graphics/FunkinSprite.hx
source/funkin/play/character/MultiSparrowCharacter.hx

* Now game is forced to *draw* graphic to actually **cache** it in application memory.
* Added texture caching gor multisparrow characters.
* _Deprecated some caching fucntions in FunkinSprite.hx_
In all menus with correctly written caching the game does not show FPS drops
In gameplay there's no FPS drops too (tested with QT REWIRED, Hellclown song form VS TRICKY V-slice port without "third party" caching and some other mods with caching)
Maybe by 0.8 it will no longer be needed, but for now it will remain useful, i guess

[OPTIMIZATION] Some additions of textures caching

---

source/funkin/util/macro/EnvironmentConfigMacro.hx

N/A
This is caused by the fact the file content is simply split by a LF line ending, so in CRLF the carriage return would be included with the value. Fortunately a simple trim solves this.
This crash was being caused by it.
It would look like this in the code lel

[FIX] Fix EnvironmentConfigMacro not parsing CRLF line endings properly

---

source/funkin/ui/freeplay/BGScrollingText.hx
source/funkin/ui/freeplay/FreeplayState.hx

I've been testing around with Nvidia Nsight to have more clear rendering debugging and found some issues that affect FreeplayState both in loading and performance. The main problem I noticed was with ``BGScrollingText``, since by creating multiple FlxText instances it also created seperate bitmaps and draw calls for each object with no batching.
I fixed this by making only one instance of text and making the rest of the sprites just copy the graphic of the main text sprite.
Also fixed the black overlay from the freeplay intro never getting set invisible, which saves some performance both with running the shader and rendering it's bitmap.
Here's a small sample of the draw calls produced by ``BGScrollingText`` before and after this change.
| Before | After |
|--------|-------|
| <video …

[OPTIMIZATION] Small Freeplay rendering optimizations

---

source/funkin/data/notestyle/NoteStyleData.hx

* Fixes notes being called props in `NoteStyleData.hx`.
*P.S. I realized while making this PR that I myself made a typo in the branch name. It's so over.*

[DOCUMENTATION/CHORE] Fix typo in NoteStyleData

---

source/funkin/modding/module/Module.hx
source/funkin/modding/module/ModuleHandler.hx

N/A
This PR adds a brand new `params` parameter to the Module constructor with a `state` parameter to go along with it.
This allows modules that can only run in a specific state, making it easier to make modules that only run in `PlayState` for example!
```haxe
import funkin.modding.module.Module;
import funkin.play.PlayState;
class SomePlayStateThing extends Module {
public function new() {
super("AAAAAAAAAAAAAAAAA", 1, {
state: PlayState
});
}
override function onUpdate(event:UpdateScriptEvent):Void {
super.onUpdate();
trace('IN PLAYSTATE!!!');
PlayState.instance.currentStage.getBoyfriend().angle += 360 * event.elapsed;
}
}
```

[ENHANCEMENT] [MODDING] Scoped Modules

---

source/funkin/modding/PolymodHandler.hx

N/A
Hot-reloading causes the function `forceReloadAssets` of `PolymodHandler` to be called, which loads back all mods and their script classes. This PR removes the line to register scripted classes.
On the surface, this change seems preposterous. However, reloading mods triggers the function `Polymod.init();` which already contains the line that is deleted in this PR. This means that this PR mitigates this monstrocity from occuring upon hot-reloading:

[OPTIMIZATION?] Prevent script classes from being registered twice after hot-reloading

---

source/funkin/modding/PolymodHandler.hx
source/funkin/ui/debug/stageeditor/components/WelcomeDialog.hx
source/funkin/util/MemoryUtil.hx

Probably not
Simple lil' PR, since OpenFL was updated we can use the new [`System.totalMemoryNumber`](https://api.openfl.org/openfl/system/System.html#totalMemoryNumber) field to get a higher range memory usage value where possible directly from OpenFL without Funkin' needing to intervene
N/A

Use System.totalMemoryNumber in MemoryUtil

---

source/funkin/Conductor.hx
source/funkin/modding/PolymodHandler.hx
source/funkin/ui/debug/stageeditor/components/WelcomeDialog.hx

Fixes #4434
Restarting a song that has BPM changes when the song has a different BPM than its starting BPM causes the song to start at the incorrect time. 
When the BPM is lower than the starting BPM, the song will start later than it should. This is noticeable in Eggnog Erect where restarting after the BPM change at the end causes the song to start two seconds after the countdown ends.
When the BPM is higher than the starting BPM, the song will start before the countdown ends. This is somewhat noticeable in Monster where restarting during its highest BPM causes the instrumental to start slightly before the countdown ends and the camera event focusing on Boyfriend happens before the countdown ends.
This happens because the time the song starts at in the countdown is based on …

[BUGFIX] Ensure Song starts at Correct time when Restarting Songs with BPM Changes

---

source/funkin/play/notes/NoteSprite.hx

Flixel batches quads when they all share the same rendering values (color, antialiasing, shader, etc). The problem with this is that, with each note having it's own hsv shader instance, batching is unavailable. Which can be pretty harmful for performance in instances with many notes on screen. To fix this I made it so the shader is disabled by default and only applied when neccesary (miss desaturation or hue changes).
Here's the difference in draw calls needed checked through Nvidia Nsight.
| Before  | After |
| <video src="https://github.com/user-attachments/assets/fddddd8b-2d3d-4d28-857a-503b6b51b709" width="320" height="240" controls></video> | <video src="https://github.com/user-attachments/assets/4636800e-b052-4873-8bdd-cc2ac2cd0907" width="320" …

[OPTIMIZATION] Improve note batching

---

source/funkin/ui/MusicBeatState.hx

Changes the documentation in `MusicBeatState.hx` as there was a typo in it. The word "byt" has now been changed to "by"

[CHORE] Fix Typo In MusicBeatState

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Fixes #3761 
When you move a bunch of items or notes and move them back into the same position and release, it removes the selection boxes on the notes for some reason.
To fix this, the code now returns if they weren't actually moved. This doesn't fix actually fix the issue in the code, it just bypasses it. I have no clue where it happens, but it has something to do with when the move command is performed but the notes don't actually need to move at all, and something note specific because it doesn't happen to events when moved but not actually moved. 
https://github.com/user-attachments/assets/b6e83955-280d-448e-bc18-6406a25c2832
~~Wait, that's weird, the move events command can still preform.~~
~~Ah, it's because dragDistanceColumns is always 8. I'll make an additional change for that …

[BUGFIX] Chart Editor - Fix selection breaking when notes are dragged to the same place

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Closes #2731
Adds hotkeys for toggling the volume of everything in the audio menu.
Shift + M for metronome
Shift + H for hitsounds
Shift + I for instrumental
Shift + V for vocals
Shift + B for Boyfriend vocals
Shift + D for Dad vocals
https://github.com/user-attachments/assets/ebe154ec-efc1-45c8-b762-bdc766cd7609

[ENHANCEMENT] Chart Editor - Toggle audio volume hotkeys

---

source/funkin/play/event/FocusCameraSongEvent.hx
source/funkin/play/event/ScrollSpeedEvent.hx
source/funkin/play/event/SetCameraBopSongEvent.hx
source/funkin/play/event/ZoomCameraSongEvent.hx
source/funkin/ui/debug/charting/toolboxes/ChartEditorEventDataToolbox.hx

Fixes #2861 
The default events didn't have minimum values set, lol.
https://github.com/user-attachments/assets/8b2f88f1-df19-4791-92b0-12bcd70258b9
_Sigh_, if I had noticed that I didn't change it to the develop branch I wouldn't of deleted the branch and perma closed the previous PR out of a worry that I did something wrong on my end.

[BUGFIX] Enforce minimum values for Chart Editor events

---

source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx

None
> [!NOTE]
> Requires https://github.com/FunkinCrew/funkin.assets/pull/218
Adds a charter field to the song metadata dialog that shows up when you're creating a new chart.
This was only done for the add variation window in an earlier PR.

Add Charter field to New Chart dialog

---

source/funkin/ui/freeplay/FreeplayState.hx

* Before this PR, whenever you got a new rank on a specific song, the new rank would be a bit bigger than the ones that were already there. The problem was that in the original code each rank have a scale of `0.9`, but the new ranks got a scale of `1`. Now this is fixed.
<div align='center'>
<table>
<tr>
<th>BEFORE (look at bopeebo rank)</th>
<th>AFTER</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/dc0268ce-c07e-4784-b434-beef2cac3a39" alt="BEFORE" width="1000"/></td>
<td><video src="https://github.com/user-attachments/assets/248d0fe5-7d21-488d-bcc7-ddd77cff8aaa" alt="AFTER" width="250"/></td>
</tr>
</table>
</div>

[BUGFIX] Fix New Rank being bigger than original ones

---

source/funkin/ui/debug/charting/ChartEditorState.hx

* Before this PR, you were able to playtest while the "Are you sure?" dialog was open in the Chart Editor. Now this small issue is gone.

[BUGFIX] Fix Playtesting While `Are you sure?` dialog is open

---

source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx

* My dumbass forgot to add `this.isHaxeUIDialogOpen = false;` when the user promptly decides NOT to leave the chart editor. Also for some reason I was making the dialog in the `ChartEditorState` class itself instead of the appropriate `ChartEditorDialogHandler` class. Both of these issues are thankfully gone now.
https://github.com/user-attachments/assets/5e7bb484-a967-428a-aeea-215c03239977

[BUGFIX] Fix the softlock caused by "Fix Playtesting While `Are you sure?` dialog is open"

---

source/funkin/play/PlayState.hx
source/funkin/play/event/SetCameraBopSongEvent.hx
source/funkin/util/Constants.hx

Adds an offset option to the camera bop event, useful for if you want the camera bopping to occur off-beat.

[Feature] Camera bop event offset

---

source/funkin/data/song/importer/FNFLegacyImporter.hx

Fixes #5535
When you go into the chart editor and you import a legacy chart, the scroll speed doesn't get applied properly and this pr fixes that so that instead of the scroll speed defaulting to 1, it gets set to the legacy chart's proper scroll speed.
A screenshot of what the scroll speed should be when importing a legacy chart such as Philly (Hard).

[BUGFIX] Fix Legacy Chart Import Not Applying Scroll Speed

---

source/funkin/graphics/shaders/PureColor.hx

Pretty basic fix, a incorrect value for the color was being added. Tested to work correctly both on web and desktop.
As a side note for the future, I believe in some instances where this shader is used, it should be replaced with color transform.
| Before | After |
| <img width="647" height="281" alt="image" src="https://github.com/user-attachments/assets/d83540ff-381b-4e7a-9e32-2955109f0dc3" /> | <img width="626" height="268" alt="image" src="https://github.com/user-attachments/assets/8523c1fc-3133-4722-8f9b-119505bd4156" /> |

[BUGFIX] Fix PureColor shader antialiasing

---

source/funkin/graphics/adobeanimate/FlxAtlasSprite.hx
source/funkin/ui/charSelect/CharSelectAtlasHandler.hx
source/funkin/ui/charSelect/CharSelectSubState.hx
source/funkin/ui/freeplay/FreeplayDJ.hx

I've noticed that in the new branch the quality setting ``HIGH`` has been stablished as the default quality setting. I believe it should be knocked down to ``MEDIUM``, as it is the recommended quality setting for flixel-animate. (Even ``LOW`` quality could be used in some instances, such as the Mr.Locked character, since their use of filters is pretty easy to optimize). This is because, specially on blur filters, some optimization techniques are added to use way smaller bitmaps without any obvious visual differences.
Here's screenshots of some characters that use filters with these changes, and no visual quality loss.
NOTE: On these screenshots the blur strength may seem lower than before. This isnt because of the lower quality use. This is because flixel-animate applies blur filters …

[feat/flixel-animate] Apply some lossless quality settings

---

hmm.json
source/funkin/graphics/FunkinSprite.hx

Ran into some issues regarding the implementation of these bounds but I believe they should be fully fixed now.
Changed a bit the behaviour too so if ``legacyBoundsPosition`` is turned on itll override the check for ``applyStageMatrix `` too, for accuracy.
This PR also bumps the version of flixel-animate as the method it used to list assets wasnt playing nice with polymod, but now it should be fully fixed and working both for base game and modded assets.

[flixel-animate] Legacy bounds fixes

---

source/funkin/ui/charSelect/CharSelectSubState.hx

None yet!
When Character Select had to be repositioned due how to flixel-animate makes atlases work, the entire process was eyeballed, leading to some object placement looking a tad bit off....
This pull request repositions all those objects to 99% match how they were before the flixel-animate switch!
https://github.com/user-attachments/assets/e565202f-3116-4b7c-ad9b-09e3695c1a1a
**SIDENOTE: I didn't change where the locks were positioned, the new one is way better/more centered**

`[feat/flixel-animate]` Nudge Character Select Objects to be consistent with pre-flixel-animate

---

source/funkin/util/plugins/NewgroundsMedalPlugin.hx

The previous medal was exported without swf rendering in mind, which took out some of the original filters from the original medal FLA from the Newgrounds API. Additionally this new medal export uses the BTA format which allows for more optimized file sizes while adding new features the original didnt have, like blend modes.
The new medal seen ingame.
https://github.com/user-attachments/assets/b00b361a-aaeb-42c7-ae65-8008dd66b292

``[flixel-animate]`` Improved NG Medal filters

---

source/funkin/ui/freeplay/FreeplayState.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/4530
Redo of #4533
The rank animation in Freeplay plays whenever you switch songs. To fix this I made the call to `refreshDisplay` in `changeSelection` always pass in a value of `false` over the default `true`.
I also changed the `changeDiff` function to only refresh the capsule display if the current difficulty has changed. (This is different from my previous PR. I found that I could do this instead of adding a new parameter to the `changeDiff` function).
Before:
https://github.com/user-attachments/assets/643d740a-2d23-44bb-8acf-0da8e47ac303
After:
https://github.com/user-attachments/assets/fa39bda3-d969-4559-bd1a-6c7d04d6bfc3

[BUGFIX] Fix Freeplay Rank Animation when switching songs

---

source/funkin/play/PlayState.hx
source/funkin/play/cutscene/VideoCutscene.hx

Closes #5872 
Upon destroying PlayState, any playing video cutscenes are not destroyed. Hence why entering a song without videos would make the game assume that you still have a video playing even when not.
https://github.com/user-attachments/assets/b0747ce2-90d8-4266-9eee-a16c73805161

[BUGFIX] Fix Video Cutscenes persisting between songs

---

.github/ISSUE_TEMPLATE/crash.yml

#5678 for the crash template. If a mod can cause a bug, it could also cause a crash. I believe this checkbox should be added to the crash template too.

[GITHUB] Add *the* checkbox to the Crash Template

---

source/funkin/ui/freeplay/FreeplayState.hx

None
The backing card has a beat hit function that pretty much never runs because of the freeplay menu not properly updating the conductor. This PR changes it so that the conductor actually updates instead of only firing once like how it is currently. Due to this change, the backing card's beat hit function actually runs.
Before
https://github.com/user-attachments/assets/8b38cdb1-8638-4de1-a280-e910f5ea3916
After
https://github.com/user-attachments/assets/855fbab9-4cf3-4bb2-9c6b-0b3e4f4282e2
Boyfriend also has the cool backing card flash thing as well. It's just that I have Pico selected because I love him a lot.

[BUGFIX] Fix Freeplay Backing Card Beat Hit

---

source/funkin/util/WindowUtil.hx

#3923
This pr adds a check to the event listener in `WindowUtil`. It checks whether haxe ui is focused or not.
Before when you were typing in a field and would press the button that is bound to the fullscreen toggle, you would toggle fullscreen.
Now this doesn't happen anymore.

[FIX] Don't allow fullscreen keybind in type fields

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Fixes #3791, fixes #4884
Audio playback in the chart editor isn't automatically stopped while a playhead is dragged around - that, and you can start playback while dragging any of them around too.
This PR fixes this for all 3 playheads - the playbar, grid, and note preview.
https://github.com/user-attachments/assets/e6d99c61-fd17-4b96-81c5-30b4a29e48e4

[BUGFIX] Stop Chart Editor audio playback when dragging playhead

---

source/funkin/play/PlayState.hx

Fixes #5595
When playing Stress (Pico Mix), restarting the song will cause the bricks to move slightly. I moved the stage reset function to be before the `onSongRetry` event so that the bricks could be repositioned in the stage script without the bricks resetting its position afterwards.
Stage reset before:
Stage reset after:
Yay the bricks are no longer like Bonnie from FNAF 1!!

[BUGFIX] Fix Stress (Pico Mix) bricks moving when restarting

---

source/funkin/ui/freeplay/FreeplayState.hx

Closes https://github.com/FunkinCrew/Funkin/issues/5956
I deadass have no idea whats up with the bug, I just replaced the state's `_constructor` variable when the player moved after getting a new rank.
https://github.com/user-attachments/assets/c93fccae-eaef-4c3b-af1d-5213df36912f

[BUGFIX] Fix hot-reloading after getting a new rank causing a crash

---

source/funkin/play/PlayState.hx

What is an "utton"?
Fixes a typo in `PlayState.hx`: "utton" -> "button"

[CHORE] Fix Typo In PlayState

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Closes #5953 
Fixes a crash with previously focused text fields and the user trying to exit via the confirmation dialog. ~What a clusterfuck~
[Gravar a tela_20250912_210733.webm](https://github.com/user-attachments/assets/70ba0d59-9746-462c-b6aa-69d2b6436852)

[BUGFIX] Fix text field related chart editor crash

---

source/funkin/play/song/Song.hx

#5910
If a song's metadata explicitly defines the voices, the game will use them without checking if they actually exist which will cause a crash later. This PR fixes this issue by only using the voices defined in the metadata if their files exist. If they don't exist, it will fallback to the default method of resolving voices. 
I tested this PR using this mod. All this mod does is replace the metadata file for Roses with the metadata file sent by the author of the linked issue:
[metadataTest.zip](https://github.com/user-attachments/files/22215133/metadataTest.zip)
If you use this mod on the release version, the game will crash when loading Roses. If you use it on a version compiled from this PR, the game will not crash.

[BUGFIX] Fallback to default if voices defined in the metadata don't exist

---

source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/toolboxes/ChartEditorOffsetsToolbox.hx

Fixes #5961 
Stops offsetsToolbox audio preview upon openning substate (PlayState)

[BUGFIX] Stop Chart Editor Offsets Window audio preview when playtesting

---

source/funkin/ui/freeplay/FreeplayState.hx

None.
Recent changes to `develop` made the Freeplay intro animations not play when you're returning from a song, this fixes those changes inadvertently making the capsule jump-in animation never play again after that.
Also did an unrelated tiny adjustment to the code cuz why not
[Gravar a tela_20250911_163538.webm](https://github.com/user-attachments/assets/71498669-a6b8-4f06-a3ae-07a121ca36fe)

[BUGFIX] Fix Freeplay capsules not playing jump-in animation after returning from stickers

---

source/funkin/util/MemoryUtil.hx

None
This memory leak was due to how Haxe always allocates new bytes when running `FileInput#readAll()`. For some reason the other methods don't seem to do this so I fixed it by simply using `readLine` instead.
(Note: The task memory here is big because I was using Tracy)
[Gravar a tela_20250914_014146.webm](https://github.com/user-attachments/assets/21c657b0-7499-4b38-b15e-38f80a047762)

[FIX] Fix memory leak with the new Debug Display on Linux

---

source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx
source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx
source/funkin/ui/debug/stageeditor/StageEditorState.hx
source/funkin/ui/debug/stageeditor/components/BackupAvailableDialog.hx
source/funkin/ui/debug/stageeditor/components/WelcomeDialog.hx

Closes #3931, fixes #3084 
Chart editor backups didn't include the song name in the save. Now they do (also renames songs to new chart if it has no name when it autosaves, but shhh, don't tell anyone that).
I've also gone ahead and done the same thing for the stage editor, and also removed the weird date and time thing the chart editor does as you can just use sys to get that (I noticed that's how the stage editor does it, so I copied it).
Requires this assets PR: funkincrew/funkin.assets#120
https://github.com/user-attachments/assets/28c34975-c4b7-4cc1-90d3-6f35e93d7deb

[ENHANCEMENT] Chart/stage name in backup filename

---

source/funkin/util/SerializerUtil.hx
source/funkin/util/macro/RegistryMacro.hx

Sometimes when converting `Bytes` directly into a `String`, a bit of gibberish would be left at the start or end, causing the json parsing process to throw an error. This PR adds automatic removal of said gibberish before parsing a json text with `SerializerUtil` and before any registry json is parsed, which would spare modders having to do this themselves or struggling to find the issue.

[ENHANCEMENT] Sanitize `.json` text before parsing

---

source/funkin/data/song/SongRegistry.hx
source/funkin/ui/debug/charting/ChartEditorState.hx
source/funkin/ui/debug/charting/handlers/ChartEditorDialogHandler.hx
source/funkin/ui/debug/charting/handlers/ChartEditorImportExportHandler.hx

Fixes #2411 
This fixes every problem reported in the linked issue and a bit more:
* Prevents charter from being able to delete  `default` variation when there's more than one variation available.
* Fixes song variation list not being saved into metadata file for `default` variation.
* Fixes chart data not being assigned its respective variation when loading from FNFC.
This was only fixed in 0.6.x for loading metadata files.
N/A

[BUGFIX] Chart Editor variation & difficulty handling fixes

---

source/funkin/ui/debug/anim/DebugBoundingState.hx

None
When exiting the animation editor, your mouse cursor stays visible unlike exiting something like the Chart Editor. Yeah, pretty self explanatory. 
Before:
https://github.com/user-attachments/assets/3aed550a-a669-46e2-8e97-606080646355
After:
https://github.com/user-attachments/assets/9cd04593-069e-45fe-a3b7-9e53c82a23f9

[BUGFIX] Fix Cursor staying visible after exiting the Animation Editor

---

source/funkin/play/character/BaseCharacter.hx
source/funkin/play/notes/notekind/NoteKind.hx
source/funkin/play/notes/notekind/NoteKindManager.hx

This pr allows for scripts  to easily override the base sing anim function with a singOveride variable. it also adds a no animation note to the chart editor!

[ENHANCEMENT] Character Singing Overrides And No anim Notes

---

source/funkin/ui/debug/charting/ChartEditorState.hx

Fixes #6125
Preferences for the chart editor are currently only saved if leaving through the confirmation dialogue or completely closing the window. This happens because the `autosave` function (which calls the `writePreferences` function) is no longer always called when leaving the chart editor.
This PR fixes the issue by adding a call to `writePreferences` to the `quitChartEditor` function.
https://github.com/user-attachments/assets/0e9274e0-8f51-4fc2-ab31-f0396e296ccf

[BUGFIX] Always save preferences when exiting the Chart Editor

---

source/funkin/play/PlayState.hx
source/funkin/play/components/HealthIcon.hx

Any issues about FPS Dependent HealthIcons
Now icons use their own tween (bopTween) to **bop**.
And also the speed of bopping accelerates at high BMP (noticeable at BMP > 190)

[ENHANCEMENT] FPS Independent health icon bopping

---

source/Main.hx

Closes #6116 
Disables the auto-localization feature so that certain UI elements don't use your system's language.
"Yes" and "No" buttons stay in English instead of Portuguese (in my case)

[BUGFIX] Disable Haxe UI auto-localization

---

source/funkin/ui/debug/anim/DebugBoundingState.hx

Closes https://github.com/FunkinCrew/Funkin/issues/4810
When changing to the animations mode in the animation editor, a lone haxeflixel icon will spawn on top of the animation dropdown. This is because the haxe ui dropdown doesnt get initialized properly when its visibility is set to false. This PR fixes this by making the animation dropdown use `hide()` and `show()` as opposed to toggling the visibility variable.
https://github.com/user-attachments/assets/b6d9e191-aaa5-4dcb-8513-d9e7ba301c89

[BUGFIX] Fix the missing object icon spawing when switching from Spritesheet to Animations

---

source/funkin/ui/transition/stickers/StickerSubState.hx

#5436 
Now transition stickers are rendered on their own OpenFL container sprite, to render them on top of the entire game, as originally intended (right, Cam?)
Preview:
https://github.com/user-attachments/assets/ddbf938d-7e1d-49f2-8b10-a4f802d13713

[ENHANCEMENT] Render Transition Stickers on OpenFL Sprite

---

source/funkin/ui/freeplay/FreeplayState.hx
source/funkin/ui/story/StoryMenuState.hx
source/funkin/ui/transition/stickers/StickerSubState.hx

https://discord.com/channels/1419268615605325907/1419276431032189038/1423371876968828942
If you were to spam escape while the stickers are de-transitioning, the stickers will persist across the game. This PR fixes it by preventing the player from ever leaving any menu with stickers (i.e. the story menu and the freeplay menu) until the stickers are done transitioning.
I don't know how to record a video of me spamming escape you just have to trust me on this one

[BUGFIX] Fix stickers persisting after exiting menus

---

source/funkin/ui/charSelect/CharIcon.hx
source/funkin/ui/charSelect/CharIconCharacter.hx
source/funkin/ui/charSelect/CharIconLocked.hx
source/funkin/ui/charSelect/CharSelectGF.hx
source/funkin/ui/charSelect/CharSelectPlayer.hx
source/funkin/ui/charSelect/CharSelectSubState.hx
source/funkin/ui/charSelect/CharacterUnlockState.hx
source/funkin/ui/charSelect/IntroSubState.hx
source/funkin/ui/charSelect/Lock.hx
source/funkin/ui/charSelect/Nametag.hx

Contribution towards https://github.com/FunkinCrew/Funkin/issues/4303
This PR adds null-safety to the following classes:
* `ui.charSelect.CharacterUnlockState`
* `ui.charSelect.CharIcon`
* `ui.charSelect.CharIconCharacter`
* `ui.charSelect.CharIconLocked`
* `ui.charSelect.CharSelectGF`
* `ui.charSelect.CharSelectPlayer`
* `ui.charSelect.CharSelectSubState` (*PARTIAL*)
* `ui.charSelect.IntroSubState` (*PARTIAL*)
* `ui.charSelect.Lock`
* `ui.charSelect.Nametag`

[CHORE] Null safety to 10 `ui.charSelect` classes

---

source/funkin/play/notes/notestyle/NoteStyle.hx

If `assets.countdownX.data.audioPath` doesn't specify any library, the game will try to handle the path as an image path, leading into a crash or whatever behavior if the wrong path actually exists
```json
...
"assets": {
"countdownThree": {
"data": {
"audioPath": "gameplay/countdown/4eva/introTHREE"
},
"assetPath": null
}
}
...
```

[BUGFIX] Crash in `NoteStyle.getCountdownSoundPath` library separator code

---

source/funkin/play/PlayState.hx
source/funkin/ui/debug/charting/ChartEditorState.hx

Closes https://github.com/FunkinCrew/Funkin/issues/6204
Loading into a song in the chart editor used to move you to the beginning of said song. This PR fixes it by introducing `targetSongPosition` to chart editor params (Conductor just kinda gets reset when going into the editor thru a song so this was the next best thing) and then moving the current scroll to that time.
https://github.com/user-attachments/assets/2bfec96b-a23f-45c5-9081-744260e60082

[ENHANCEMENT] Make the chart editor open the current song at the current timestamp
